### ISSUE TITLE
interacting with the heroku

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize-auto#10]
Hi,

Trying to generate the models from the Heroku db, received the next error:
~~~
ERR: error: no pg_hba.conf entry for host "IP", user "user", database "database", SSL off
~~~

As I understand the case is in the SSL. Do we have any method to overcome this?

Regards,

**Comment by ianseyer** [comment]
Had the same issue.

After adding 
`ssl: true` 
to the JSON config AND the connection URI, I found the solution to be, in bash:
`export PGSSLMODE=require`

Note that you will have to set that environment variable each time you wish to connect to the database, so it might be worth setting it from your boot script.

**Comment by PavelPolyakov** [comment]
@ianseyer 
in my case it was solved the next way, probably it would help you either.

```
var sequelize = new Sequelize(config.get('database.database'), config.get('database.username'), config.get('database.password'), {
    dialect:  'postgres',
    protocol: 'postgres',
    port:     config.get('database.port'),
    host:     config.get('database.host'),
    logging:  debug, //false

    dialectOptions: {
        ssl: true
    },

    pool: {
        max: 20,
        min: 0,
        idle: 5000
    }
});
```

**Comment by durango** [comment]
Should be doable with the `-c` option. Thanks!

**Comment by IsmaelTerreno** [comment]
In my case was more accurate add the 'dialect' , 'protocol' with 'postgres' and works pretty well:

`{
      ...
      dialect:  'postgres',
      protocol: 'postgres',
     ...
    }`
Here is a good explanation to how to connect a heroku DB:
https://sequelize.readthedocs.io/en/1.7.0/articles/heroku/

Hope this helps more people.
