### ISSUE TITLE
Unable to fetch model schema from remote db?

### ISSUE THREAD

**Issue by samelliott89** [sequelize/sequelize-auto#105]
I'm trying to fetch model info with sequelize-auto from a remote db. Is this possible? My assumption is that it's not, but I'm not getting an error when I run it from the CLI.

**Comment by aspdev91** [comment]
Hi Sam, I was able to connect to the db, query it, and receive a "Done!" message. However, it's not returning any files.

**Comment by elyfran** [comment]
????

**Comment by durango** [comment]
Please update sequelize-auto and retry, feel free to re-open the ticket if you're still experiencing issues.
