### ISSUE TITLE
Setting schema in -c but not working

### ISSUE THREAD

**Issue by elyfran** [sequelize/sequelize-auto#108]
Hi,

I set schema in -c but not work.

Example:

{
    "additional" :{
      "timestamps": false,
      "freezeTableName": true,
      "schema": "db_teste"
    }
}

Msg:

Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
Done!

**Note that the schema has not changed and remains public.

**Comment by TechMaster** [comment]
Same problem as mine !

**Comment by bpowell415** [comment]
showAllTables that this library uses is provided by sequelize and is hard coded to the public schema. it doesn't allow you to specify the schema. there is a method that allows you to specify a schema but you have to specify table name as well. This is something that sequelize people need to address. Or this library would need to be updated to allow specifying a table and schema. this would reduce the "automated" nature and force you to specify tables, but it would be a workaround until sequelize allows you to specify a schema for postgres when you setup the sequelize object

**Comment by durango** [comment]
This is now fixed within `master`/next patch version, I would remove the `schema` flag out of the `additional` block though.

**Comment by rafaelsplima** [comment]
How did they solve it?
