### ISSUE TITLE
Sequelize-auto doesn't support PostgreSQL schemas

### ISSUE THREAD

**Issue by mconsoni** [sequelize/sequelize-auto#113]
The schema 'public' is hardcoded in lib/dialects/postgres/query-generator.js, it's not possible to list tables in other schema.
I'm using `master` branch.

The code I'm using is:

>
>     var auto = new SequelizeAuto(dbConfig.db, dbConfig.user, dbConfig.pass,
>                {
>                   host: dbConfig.host,
>                    dialect: 'postgres',
>                    port: dbConfig.port,
>                    additional: {
>                        timestamps: false
>                    },
>                    tables: [ table ],
>                    directory: './auto-models',
>                    schema: config.uploadSchema,
>                    logging: false,
>                });
>            
>     auto.run(function(err) {
>       if (err)
>            return cb(res, err);
>
>       console.log(auto.tables);

And `auto.tables` is empty when 2 tables are created.

I fixed it,  I have prepared a PR but I have to continue reading how to get access.

**Comment by zlatinejc** [comment]
What is the status on this fix ?

**Comment by durango** [comment]
@mconsoni where's the PR?

**Comment by durango** [comment]
Schemas should now be supported

**Comment by remojansen** [comment]
How can you use it when a database has multiple schemas? Can I use table names with schema prefixes?
