### ISSUE TITLE
Thanks for the awesome project.

### ISSUE THREAD

**Issue by andyforever** [sequelize/sequelize-auto#114]
I have create a desktop app to export sequelize model from database automatically.
Welcome to have a try.
https://github.com/andyforever/sequelizer
![sequelizer](https://camo.githubusercontent.com/947fd823085437881c1b18918633f3dbaa5d718b/68747470733a2f2f67772e616c6963646e2e636f6d2f7470732f5442315a574c47505858585858636f5846585858585858585858582d313732302d313136302e706e67)

**Comment by durango** [comment]
Added your project to the README, thanks! :+1:
