### ISSUE TITLE
how does this work ?

### ISSUE THREAD

**Issue by moeinrahimi** [sequelize/sequelize-auto#118]
hi
in my code i have this
````
var auto = new SequelizeAuto('database', null,null, {
    host: 'localhost',
    dialect: 'sqlite',
    tables: ['routes'],
    storage: './database' 
})
````

where the model is going to store ?

**Comment by ihorskyi** [comment]
@moeinrahimi by default it is `__directory + '/models'`. 
You can also specify custom directory via `directory` property. 
```javascript
var auto = new SequelizeAuto('database', null,null, {
    host: 'localhost',
    dialect: 'sqlite',
    tables: ['routes'],
    directory:'./my_custom_dir',
    storage: './database' 
})```

**Comment by moeinrahimi** [comment]
@ihorskyi 
thanks for quick reply,
it's not working, it should make a routes.js file right ? i created models directory and also tried with custom directory but nothing happens,

**Comment by ihorskyi** [comment]
That's right, it should create `routes.js` file. You could also try removing `tables: ['routes'],` and run without table specified.
Also check if that `'./database'` is db is not empty

**Comment by moeinrahimi** [comment]
@ihorskyi 
ok, it's not working like before, tried to test it without tables and also checked my database it's not empty it has a 'routes' table.

**Comment by moeinrahimi** [comment]
@ihorskyi any idea on what's the issue ? i'm on linux, maybe permission issue ? of course i tried that.
i really need this

**Comment by ihorskyi** [comment]
@moeinrahimi did you resolve your issue? Looking at your output it states that table are empty: `tables: {},`

My guess is that you need to point `sequelize-auto` to actual db location, for example

`storage : './database/test_db.db'`
instead of
`storage: './database'`

I would also suggest to provide a full path (just to test), for example
`storage : '/home/user/dev/database/test_db.db'`

**Comment by durango** [comment]
Latest patch should help alleviate problems like this with sqlite, please update and try again. Reopen the issue if there's still a problem.
