### ISSUE TITLE
-o does not work

### ISSUE THREAD

**Issue by kentonbmax** [sequelize/sequelize-auto#120]
I keep trying to update my models located in root/server/models and it always creates the files in root/models

**Comment by ihorskyi** [comment]
@kentonbmax Could you please provide a whole command line of the way you doing it?

**Comment by kentonbmax** [comment]
Please see below exec from terminal in VSC using gulp at app level. 

gulp.task('updateModels', function (cb) {
  exec('cd node_modules')
  exec('sequelize-auto -o "./server/models" -h localhost -d <Db> -u <user> -x <pass> -c ./sqlConfig.json', function (err, stdout, stderr) {
    console.log(stdout);
    console.log(stderr);
    cb(err);
  });
})

**Comment by ihorskyi** [comment]
@kentonbmax ok, few more questions - 
* are you sure it does really updates files in `root/models`? For example you could remove those files from `root/models` and run script again.
* sequelize-auto installed locally or globally?
* Why you perform `exec('cd node_modules')` and run `sequelize-auto` from that directory?
* Could you please also paste console output?

**Comment by kentonbmax** [comment]
If I remove the folder root/models, it is recreated when running the script. It is installed globally. I'm evaluating potentially automate updating the models from database changes. Similar to EF.

**Comment by ihorskyi** [comment]
Actually this looks weird with empty param values for `-d -u -x`. Are those values including dialect provided in `sqlConfig.json`?
Could you please also show its content?
Another thing - is it working correctly when you run it just from terminal, not from gulp:

`sequelize-auto -o "./server/models" -h localhost -d DB -u USER -x PWD`

**Comment by kentonbmax** [comment]
It does work and the models get updated, just not the to the specified directory. The config only is used to specify the instance name for the sql database as you cannot through the server param. Not including the db, user name and password in this context.

**Comment by ihorskyi** [comment]
@kentonbmax unfortunately without `sqlConfig.json` provided it's impossible to guess other options, especially a `dialect` :)

**Comment by kentonbmax** [comment]
{
        "dialect": "mssql",
        "dialectOptions": {
            "instanceName": "instanceName"
        }
 }

**Comment by kentonbmax** [comment]
@ihorskyi any update on this? Hoping to pull it in to my template.

**Comment by durango** [comment]
<img width="184" alt="screen shot 2017-03-20 at 1 52 21 pm" src="https://cloud.githubusercontent.com/assets/677683/24113843/7a194044-0d74-11e7-990a-3b515de9c3b3.png">

@kentonbmax are you sure that you have writing permissions/correct connection settings/etc? Try writing the full path, or set the `cwd` option in `exec()`

**Comment by kentonbmax** [comment]
@ihorskyi I provided the exact command that I'm executing and my json from sqlConfig.json. Please fill in the user, database, and password specific to your example when testing.

**Comment by durango** [comment]
@kentonbmax I just patched this, should be good for version `0.4.23`

**Comment by durango** [comment]
Closing the issue, if there's still a problem feel free to re-open the thread
