### ISSUE TITLE
Change implementation from async callbacks to promises (q)

### ISSUE THREAD

**Issue by fnkygy** [sequelize/sequelize-auto#123]
When integrating with code which uses promises heavily, it is seen that initialisation of the models can take longer than usual, resulting in inconsistent behaviour.

Example:
var model; /* global variable */
auto.run(function(err) {
  if(err) throw err;
  model = Sequelize.define('table_name',auto.tables.table_name);
});

// Business Code
model.create({...}) -> Can throw an error if 'model' is not yet assigned

Promises are a much better way of providing flexibility to callers, so that callers can choose to wait till the model is assigned.

**Comment by steveschmitt** [comment]
Fixed in 0.6.0
