### ISSUE TITLE
mssql doesn't work for me. Simply outputs nothing

### ISSUE THREAD

**Issue by neilyoung** [sequelize/sequelize-auto#124]
` sequelize-auto -o "./models" -h xxx.xxx.xxx.xxx -u xxx -x xxx -p 1433 -e mssql -d xxx 
`

Simply no output. Returns after a second with nothing, no error, no exception. Any chance to get behind?

PS: Running on a MAC. Tedious NPM installed. Sequelize generally works with that DB

**Comment by durango** [comment]
Running on a mac osx as well and using Amazon's RDS for a MSSQL server, have no issues connecting to / creating models. Can you update sequelize-auto and tedious and retry again please. If you're still having issues feel free to re-open the ticket.

**Comment by neilyoung** [comment]
Maybe it is an issue with the server version or the server configuration. Mine is a "special configured" SQLServer 2008 R2

**Comment by durango** [comment]
What version of sequelize-auto are you using? Please update to the latest, if you could provide me the command line that you're running and if you can setup a username/pass/database for me that would be even more helpful. Otherwise I'm just throwing darts in the dark and wouldn't be able to solve anything.

**Comment by durango** [comment]
On appveyor I just got this:

```
sqlcmd -S "(local)" -U "sa" -P "Password12!" -d "master" -Q "CREATE DATABASE [sequelize_auto_test]; ALTER DATABASE [sequelize_auto_test] SET READ_COMMITTED_SNAPSHOT ON;"
sqlcmd : Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [2]. .
At line:1 char:1
+ sqlcmd -S "(local)" -U "sa" -P "Password12!" -d "master" -Q "CREATE D ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Sqlcmd: Error: ...L Server [2]. .:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is 
correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Command executed with exception: Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```
Please make sure that you have remote connections available

**Comment by durango** [comment]
https://www.appveyor.com/docs/services-databases/#enabling-tcpip-named-pipes-and-setting-instance-alias this might be able to help you
