### ISSUE TITLE
ForeignKey also as unique constraint generates reference with null values

### ISSUE THREAD

**Issue by palanik** [sequelize/sequelize-auto#125]
Hi,
When I keep my ForeignKey also as unique (together with another field) constraint on my PostgreSQL db, the `references` object in generated model has nulls.

```JS
      references: {
        model: 'null',
        key: 'null'
      }
```

I think the `unique constraint` is overwriting the `foreign key` fields.

I came across [this function](https://github.com/sequelize/sequelize-auto/blob/master/lib/dialects/index.js#L119-L121) in the code and I believe it was written for this purpose.
Currently, the function not used in code, but only on test.

HTH.

Thx.

**Comment by zlatinejc** [comment]
I am also experiencing the same issue.

I have constraint rules applied to foreign keys, unfortunatelly i get the same null values in he generated model.

It would be nice to fix this.

**Comment by durango** [comment]
What does your schema look like?

**Comment by zlatinejc** [comment]
If affects any pair of entites conected via FK.
The trick is when I apply different CONSTRAINT CHECKs to fields that are FK, then I always get refeences with null values in model & key.

**Comment by durango** [comment]
Should be fixed within master, please let me know.

**Comment by zlatinejc** [comment]
Work like a charm, although Sequelize seems it cannot inlcude models if an attribute is not a primary key :(

**Comment by durango** [comment]
@zlatinejc could you open a new issue with a copy of the schema that's giving you issues please?
