### ISSUE TITLE
How to include all tables, but exclude certain tables?

### ISSUE THREAD

**Issue by subatomicglue** [sequelize/sequelize-auto#126]
We have one bad view, with broken foreign key ref, in our MySQL, which we are keeping as a backup if needed.  We dont want to spend the time to fix, and actually want to keep it "just in case"...

When running Sequelize-Auto, we get exceptions when reading those tables.   Using try/catch, I cannot suppress the error.   Also, Sequelize only has "--tables" for the command line, to **include** tables, but there is no way to **exclude** tables to prevent even attempting to read them.

```
try {
  var SequelizeAuto = require('sequelize-auto');
  var auto = new SequelizeAuto(db, user, pass, {
      host: host,
      dialect: 'mysql',
      directory: "./src/models_sequelize_auto", // prevents the program from writing to disk
      port: port,
      additional: {
          timestamps: false
      },
      define: { timestamps: false },
      pool: { max: 5, min: 0, idle: 10000 },
      logging: false,
      // tables: ....    // I dont want to use this, I actually want to __exclude__ certain tables, but include everything else.
  });

  auto.run(function (err) {
    // never gets hit:
    if (err) console.log( "================================\nERROR: " + err );

    //console.log(auto.tables); // table list
    //console.log(auto.foreignKeys); // foreign key list
  });
}
catch (err) {
    // never gets hit:
    console.log( "================================\nERROR: " + err );
}

```

**Comment by durango** [comment]
@subatomicglue any chance you could copy & paste the relevant SQL for the schema to test locally?

**Comment by ihorskyi** [comment]
Some time ago we had similar issue - there were 52 tables, 13 of them were legacy tables which we could not remove yet, and at the same time we did not want them in our node services.
PR posted

**Comment by durango** [comment]
@ihorskyi thanks, @subatomicglue the latest npm version has this patch
