### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by oneofakind007** [sequelize/sequelize-auto#128]
Hello Team,

I tried to run the command below and I get this kind of error:

C:\.......\AppData\Roaming\npm\sequelize-auto -o "./models" -d testdatabase -h localhost -e mysql -p 123123

C:\........\sequelize-auto\node_modules\yargs\node_modules\camelcase\index.js:4
        let isLastCharLower = false;
        ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

got any solution for this? or anything I missed out on my installation?

**Comment by ihorskyi** [comment]
@oneofakind007 What's your node version? I bet it is < 4

**Comment by durango** [comment]
Yup, just need to upgrade node or use `babel-node` prefix

**Comment by oneofakind007** [comment]
it says here v0.10.13 and im running on windows OS
