### ISSUE TITLE
support generation of 'sequelize-json'

### ISSUE THREAD

**Issue by subatomicglue** [sequelize/sequelize-auto#130]
I wrote this python script to post process the `sequelize` .js models which are output by `sequelize-auto`

It adds in the `sequelize-json` stuff which makes MySQL JSON column string values automatically `JSON.parse` into JavaScript objects
https://www.npmjs.com/package/sequelize-json

Would be awesome to be able to hook into `sequelize-auto` to have it generate that code instead of my python script :)   Is there a way currently?

The below script Turns this:
```
column_name: {
	type: DataTypes.JSON,
	allowNull: true
},
```

Into This:
```
column_name: JsonField(sequelize, 'table_name', 'column_name'),
```

The python script:
```
#!/usr/bin/env python

import sys
import os
import re

num_args = len(sys.argv)

for filename in sys.argv[1:]:
    data = open(filename, 'r').read()

    # extract the model name
    model_name = "unknown"
    matchObj = re.search(r"define\('([^']+)'", data)
    if matchObj:
        model_name = matchObj.group(1)

    # column_name: {
    #   type: DataTypes.JSON,
    #   allowNull: true
    # }
    p = re.compile(r"([\t ]+)([\S^:]+): {(\n)([\t ]+)([\S^:]+):\sDataTypes.JSON[^}]+}")
    data = p.sub('\\1\\2: JsonField(sequelize, \'' + model_name + '\', \'\\2\')',data)

    # column_name: DataTypes.JSON
    p = re.compile(r"([\t ]+)([\S^:]+):\sDataTypes.JSON")
    data = p.sub('\\1\\2: JsonField(sequelize, \'' + model_name + '\', \'\\2\')',data)

    # /* jshint indent: 1 */
    p2 = re.compile(r"/\* jshint indent: 1 \*/(\n)")
    data = p2.sub('/* jshint indent: 1 */\\1\\1\\1let JsonField = require(\'sequelize-json\'); // use JsonField(db, \'TableName\', \'ColumnNameOfJsonType\') anywhere you\'d normally use DataTypes.JSON\\1',data)

    #f = open(filename, 'w')
    #f.write( data );
    print( data )
```

**Comment by durango** [comment]
What does your schema initially look like? You can use the API and go through the table(s) like so https://github.com/sequelize/sequelize-auto#programmatic-api

**Comment by steveschmitt** [comment]
I think sequelize now supports [JSON datatypes](https://sequelize.org/master/manual/other-data-types.html#json--sqlite--mysql--mariadb-and-postgresql-only-) natively.
