### ISSUE TITLE
Autoincrement not recognized correctly

### ISSUE THREAD

**Issue by zlatinejc** [sequelize/sequelize-auto#134]
If I create and delete and then recreate primary key at the sam column name ("id") I get this model generated:

```javascript
 id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: "nextval("Sensor_id_seq"::regclass)",
      primaryKey: true
    }
```
`defaultValue: "nextval("Sensor_id_seq"::regclass)"`, this part fails at parsing a model in Node.js.

I think I should be getting something like this:

```javascript
id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      autoIncrement: true, \\ defaultValue: "nextval("Sensor_id_seq"::regclass)",
      primaryKey: true
    }
```
I am woindering where did I loose the **autoIncrement** flag ?

Thanks in advance!

DB: PG 9.6

**Comment by sdemurjian** [comment]
+1 also does not work for MSSQL with something like the following. `TemplateId` is autoincrementing.

```
CREATE TABLE [SavedTemplate]
(
  TemplateId[int] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Template [varchar] (max) NOT NULL
)
```

**Comment by zlatinejc** [comment]
it was referenced #134 by this PR.

**Comment by durango** [comment]
Just tried it locally and it was fine, are you sure the column is primary key'd? What's your exact SQL commands/procedure (since I can't replicate it).

**Comment by zlatinejc** [comment]
Here is my CREATE SCRIPT:
```sql
-- Table: public."Sensor"

-- DROP TABLE public."Sensor";

CREATE TABLE public."Sensor"
(
    "idSensorType" integer NOT NULL,
    "idNode" integer NOT NULL,
    unit text COLLATE pg_catalog."default" NOT NULL,
    "idDatasource" integer,
    topic text COLLATE pg_catalog."default" NOT NULL,
    "uuidTopic" text COLLATE pg_catalog."default",
    id integer NOT NULL DEFAULT nextval('"Sensor_id_seq"'::regclass),
    CONSTRAINT "Sensor_id_key" UNIQUE (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."Sensor"
    OWNER to postgres;

-- Trigger: create_ds

-- DROP TRIGGER create_ds ON public."Sensor";

CREATE TRIGGER create_ds
    AFTER INSERT
    ON public."Sensor"
    FOR EACH ROW
    EXECUTE PROCEDURE after_insert_create_ds();

-- Trigger: create_uuidTopic

-- DROP TRIGGER "create_uuidTopic" ON public."Sensor";

CREATE TRIGGER "create_uuidTopic"
    BEFORE INSERT
    ON public."Sensor"
    FOR EACH ROW
    EXECUTE PROCEDURE before_insert_create_uuidTopic_by_node_id();
```

**Comment by durango** [comment]
Where are you setting `id` as a `PRIMARY KEY`?

**Comment by zlatinejc** [comment]
I updated It still does not work. 
It appears if you create a table and add columns later, somthing strange happens.

**Comment by durango** [comment]
What does this SQL command give you?

```sql
SELECT 
      o.conname AS constraint_name, 
      (SELECT nspname FROM pg_namespace WHERE oid=m.relnamespace) AS source_schema, 
      m.relname AS source_table, 
      (SELECT a.attname FROM pg_attribute a WHERE a.attrelid = m.oid AND a.attnum = o.conkey[1] AND a.attisdropped = false) AS source_column, 
      (SELECT nspname FROM pg_namespace WHERE oid=f.relnamespace) AS target_schema, 
      f.relname AS target_table, 
      (SELECT a.attname FROM pg_attribute a WHERE a.attrelid = f.oid AND a.attnum = o.confkey[1] AND a.attisdropped = false) AS target_column, 
      o.contype, 
      (SELECT d.adsrc AS extra FROM pg_catalog.pg_attribute a LEFT JOIN pg_catalog.pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid,  d.adnum) WHERE NOT a.attisdropped AND a.attnum > 0 AND a.attrelid = o.conrelid LIMIT 1) 
    FROM pg_constraint o 
    LEFT JOIN pg_class c ON c.oid = o.conrelid
    LEFT JOIN pg_class f ON f.oid = o.confrelid
    LEFT JOIN pg_class m ON m.oid = o.conrelid
    WHERE o.conrelid = (SELECT oid FROM pg_class WHERE relname = 'Sensor' LIMIT 1)
```

**Comment by zlatinejc** [comment]
![image](https://cloud.githubusercontent.com/assets/10756198/24114300/ff075c7a-0d9f-11e7-9e9f-a80a0cc62f32.png)

**Comment by zlatinejc** [comment]
I can reproduce it:

1. create empty table
2. add one attribute (name)
3. add another one (id)
4. add primary key to attribute one

It looks like the order of column creation matters.
If I create the id field first, everything works ok.

Any ideas ?

**Comment by durango** [comment]
Unfortunately it still works great for me, I'll need the exact order in which you execute your SQL commands to replicate

**Comment by zlatinejc** [comment]
I am thinking it might be related to pgAdmin I am using, will try to replicate it via script commands.

**Comment by zlatinejc** [comment]
Voilà, simple steps to reproduce via command line:

```javascript
CREATE TABLE public."SensorOmega" ()
ALTER TABLE public."SensorOmega" ADD COLUMN "name" TEXT
CREATE SEQUENCE "SensorOmega_id_seq";
ALTER TABLE public."SensorOmega" ADD COLUMN id integer NOT NULL DEFAULT nextval('"SensorOmega_id_seq"'::regclass)
ALTER TABLE public."SensorOmega" ADD CONSTRAINT "SensorOmega_pkey" PRIMARY KEY (id);
```
So, that takes pgAdmin off the board ...
Interesting ...

**Comment by zlatinejc** [comment]
And another potential bug: sequence names are not escaped correctly if they inlcude double quotes,
will open another issue

**Comment by durango** [comment]
I honestly wont be able to convert every single default value use case into an actual function but the values are at least escaped for parsing within `master`. Let me know

**Comment by zlatinejc** [comment]
Hi!

Although escaping now worksm, yet unfortunately this only closes issue #136 

```javascript
id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 'nextval("Sensor_id_seq"::regclass)',
      primaryKey: true,
      unique: true
    }
```

My desired goal is to have a:

```javascript
autoIncrement : true
```

Instead of:

```javascript
defaultValue: 'nextval("Sensor_id_seq"::regclass)',
```

**Comment by durango** [comment]
Does sequelize actually handle this properly though? A sequence isn't necessarily an increment but an increment is a sequence.

**Comment by bmburhan22** [comment]
autoIncrement:true, autoIncrementIdentity:true
made it work
