### ISSUE TITLE
Grabing models from mssql database sets some fields types' :    `type: "BIT"`

### ISSUE THREAD

**Issue by VovanSuper** [sequelize/sequelize-auto#139]
Example of generated model : 

module.exports = function(sequelize, DataTypes) {
	return sequelize.define('AspNetUsers', {
		Id: {
			type: DataTypes.STRING,
			allowNull: false
		},
		Email: {
			type: DataTypes.STRING,
			allowNull: true
		},
		EmailConfirmed: {
			type: "BIT",
			allowNull: false
		},
		PasswordHash: {
			type: DataTypes.STRING,
			allowNull: true
		},
		SecurityStamp: {
			type: DataTypes.STRING,
			allowNull: true
		},
		PhoneNumber: {
			type: DataTypes.STRING,
			allowNull: true
		},
		PhoneNumberConfirmed: {
			type: "BIT",
			allowNull: false
		},
		TwoFactorEnabled: {
			type: "BIT",
			allowNull: false
		},
		LockoutEndDateUtc: {
			type: "SMALLDATETIME",
			allowNull: true
		},
		LockoutEnabled: {
			type: "BIT",
			allowNull: false
		},
		AccessFailedCount: {
			type: DataTypes.INTEGER,
			allowNull: false
		},
		UserName: {
			type: DataTypes.STRING,
			allowNull: false
		}
	}, {
		tableName: 'AspNetUsers'
	});
};

Fields `EmailConfirmed` is: "bit not null",
       LockoutEndDateUtc is "smalldatetime null"
P.S. no automatic "freezeTableName" setting to true (as wished)

**Comment by VovanSuper** [comment]
So which Sequelize.DataType should I subsrtitube those with (in db, for example, `EmailConfirmed` set to `0` or `1`; if then using `boolean` how to remap to existing db (cannot touch the db, i.e no changes )

**Comment by VovanSuper** [comment]
Additional error trying to sync to database : '{ SequelizeBaseError: Column names in each table must be unique. Column name 'Id' in table 'AspNetRoles' is specified more than once.\n '

**Comment by durango** [comment]
For the BIT to Boolean you'll have to install from master (npm version is not patched yet) and not sure about your Id problem.. in the generated output there's only one Id so there's no problem there. Perhaps you shouldn't be syncing? (sync: false)

P.S. if you ever need to change anything to suit your specific schema feel free to use the programmatic API (examples are in the README).

**Comment by VovanSuper** [comment]
Well, anyways, after grabbing mssql's tables, importing and, obviously, querying the Db, inconsistency error due to ```timestamps: false``` isn't being set (and table attrs are added, like 'updatedAt'...), which requires to add the attr by hands. Should this be considered as a bug, really?

**Comment by durango** [comment]
Honestly you're most likely doing something wrong, `updatedAt` does not get added automagically, we have mssql test to prove this. You can set additional options such as `timestamps: false` using the `-a` flag (please look at the README).

**Comment by steveschmitt** [comment]
I think this is fixed in `sequelize-auto@0.5.0`
Please try it and close the issue if so.  Thanks!

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`.
