### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by remojansen** [sequelize/sequelize-auto#140]
Hi guys,

Thanks for all your work on Sequelize and this project. I'm building some apps with TypeScript these days and I was wondering if you guys would consider adding support for TypeScript?

If you are I would be happy to help with that and send a PR...

I would need some help, not with TypeScript, but with the architecture to support multiple outputs.

We should do it generic to allow other kinds of support (e.g. flowtype)

Thanks!

**Comment by durango** [comment]
Would appreciate a PR, take a look at the programmatic API should be the starting point

**Comment by remojansen** [comment]
I'm working on this now but I need some helo with the tools. How do you run the unit test in dev? I saw the npm command but it fails because I don't have a database available. I can create a pg instance but I would like to know if there is already something in the library that helps me to create default testing db automatically? thanks!

**Comment by steveschmitt** [comment]
With the 0.6.4 release, we have completely changed the way we generate TypeScript files.  Now it is more like the [TypeScript usage](https://sequelize.org/master/manual/typescript.html#usage) example in the Sequelize documentation.

The "db" file is now called `init-models.ts`.  There is a brief example of usage in the [README](https://github.com/sequelize/sequelize-auto/blob/master/README.md#typescript).

Also note the **sample** directory in the repo, which has scripts for creating sample databases in 4 different dialects.

Please give it a try and let me know how it goes.

**Comment by Shahor** [comment]
Although the typings are produced by the library (I can see them in the node_modules directory), they don't seem to be exported correctly. 

![image](https://user-images.githubusercontent.com/204561/96993346-7bd0f180-152b-11eb-85bc-b512240733d1.png)

![image](https://user-images.githubusercontent.com/204561/96993368-825f6900-152b-11eb-8073-3bddad8cc6fe.png)


Is there specific to be done here to make ts properly take the typings?

**Comment by steveschmitt** [comment]
@Shahor the types are exported correctly in release 0.6.5.
```js
import { SequelizeAuto } from "sequelize-auto";

const auto = new SequelizeAuto(config.dbName, config.user, config.password, options);

auto.run().then(data => {
  const tableNames = Object.keys(data.tables);
  console.log(tableNames);    // list of tables that were exported
});
```

**Comment by Shahor** [comment]
Great, thanks!
