### ISSUE TITLE
TIMESTAMP fields in Postgresql being recognised as DataTypes.Time instead of DataTypes.Date

### ISSUE THREAD

**Issue by anttyc** [sequelize/sequelize-auto#143]
Heyo,

Thanks for the great work with sequelize and this generator. 

I found that fields defined in Postgresql as 'TIMESTAMP WITH TIME ZONE' or 'TIMESTAMP' are being generated as DataTypes.Time. It looks like the code for string matching doesn't take into account 'timestamp' so it matches with 'time'. Seems like a quick fix but I wanted to make sure I wasn't missing something. I could submit a PR with the change if it's alright.

Cheers,
Chris

**Comment by simon-p-r** [comment]
When will this fix be published to npm?

**Comment by magicsky** [comment]
But MySQL timestamp should be `DataTypes.TIME`, otherwise the `toJSON()` will be failed.

**Comment by steveschmitt** [comment]
I think this is fixed in `sequelize-auto@0.5.0`
Please try it and close the issue if so.  Thanks!
