### ISSUE TITLE
-h not working, instead, it using my local ip

### ISSUE THREAD

**Issue by brucejcw** [sequelize/sequelize-auto#146]
`sequelize-auto -o "./test"  -h "10.10.1.1" -d "tt" -u "tt" -p 3306 -x "xxx" -e "mysql" -t "tablexxx"`  

![default](https://cloud.githubusercontent.com/assets/8085088/25125389/409d5810-2461-11e7-87b7-a5f581cace03.png)

**Comment by AskYous** [comment]
I've been using sequelize-auto without quotes around my hostname. Does that fix it?
