### ISSUE TITLE
How to contribute? Dev environment setup?

### ISSUE THREAD

**Issue by remojansen** [sequelize/sequelize-auto#149]
Hi, I'm trying to work on #140 but I'm having some trouble configuring my environment. There is no `CONTRIBUTING.md` file with instructions.

I need some helo with the tools. How do you run the unit test in dev? I saw the npm command but it fails because I don't have a database available. I can create a pg instance but I would like to know if there is already something in the library that helps me to create default testing db automatically? 

If you there nothing automated I can contribute a sh script that uses docker containers to create database instances?

Thanks!

**Comment by durango** [comment]
A script that creates docker containers for DB instances would definitely be helpful. Had some issues with MSSQL & Docker before so gave up on that (this was a very long time ago).

**Comment by steveschmitt** [comment]
Updated README with some information about setting up the unit tests.
