### ISSUE TITLE
Error while auto-generating models

### ISSUE THREAD

**Issue by cliffon** [sequelize/sequelize-auto#150]
$ sequelize-auto -o "./models" -d database_development -h localhost -u cliff -p
 3306 -x 123 -e mysql
{ [SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'c
liff'@'localhost' (using password: YES)]
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'cliff\'@\'localhost
\' (using password: YES)',
  parent:
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'cliff'@'localhost'
(using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true },
  original:
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'cliff'@'localhost'
(using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true } }
Done!

**Comment by lfernando-silva** [comment]
Probably it is a problem with permission (at the database or at the computer). I already had a similar problem, that I solved using SUDO after the command. If it not solves for you, maybe you may check the db permissions

**Comment by steveschmitt** [comment]
You can try creating the Sequelize instance first, and then pass that to SequelizeAuto, as described in the [README](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api).
