### ISSUE TITLE
Does sequelize-auto supports arrays?

### ISSUE THREAD

**Issue by roytz** [sequelize/sequelize-auto#151]
I have a schema on my pg database with a field which is an array of strings (varchar(255)).
When I use sequelize-auto I get that field like this-
```
tags: {
            type: "ARRAY",
            allowNull: false,
            defaultValue: '(ARRAY[]'
        },
```
while it should've been something like-
```
tags: {
            type: DataTypes.ARRAY(DataTypes.STRING),
            allowNull: false,
            defaultValue: []
        },
```
and all the other fields are okay (defined as `DataTypes.*`). Only the array field is messed up. Why is that?

**Comment by mariusa** [comment]
This still doesn't work on 0.5.4. 
Extracted model is of type ```DataTypes.ARRAY```, should be ```Sequelize.ARRAY(Sequelize.TEXT)``` (or the array type)

**Comment by mariusa** [comment]
Hi @steveschmitt , 

The current generated code (`DataTypes.ARRAY`), gives a nodejs error.
If the actual type is unknown to have the proper fix, could the code be generated as `DataTypes.ARRAY(DataTypes.TEXT)` ?
At least this won't error. This issue should be left open until the proper fix.

**Comment by steveschmitt** [comment]
Hmm.  I don't know if it is better to have the wrong type, or to throw an error and fail fast.

**Comment by mariusa** [comment]
What about this:

```
CREATE TABLE trips2(
    id TEXT,
    permissions TEXT[] DEFAULT '{}' -- eg admin,reports,manage-orders
);
COMMENT ON COLUMN trips2.permissions IS 'TEXT';
```

Extracted data is
```
'public.trips2': {
    id: {
      type: 'TEXT',
      allowNull: true,
      defaultValue: null,
      comment: null,
      special: [],
      primaryKey: false
    },
    permissions: {
      type: 'ARRAY',
      allowNull: true,
      defaultValue: '{}',
      comment: 'TEXT',
      special: [],
      primaryKey: false
    }
  }
```
When type=ARRAY, use the comment value to generate `DataTypes.ARRAY(DataTypes.TEXT)`

**Comment by steveschmitt** [comment]
That would work, but do most postgres databases have the array data type in a comment?

**Comment by mariusa** [comment]
No, but can be easily added if mentioned in console log.
It's best to have an easy solution instead of not supporting arrays at all.
This issue could still be left open until the ideal solution is available.

Marius

**Comment by steveschmitt** [comment]
Added array element types in release **0.7.0**
