### ISSUE TITLE
Reference different schemas under the same database? 

### ISSUE THREAD

**Issue by themauveavenger** [sequelize/sequelize-auto#16]
How can I build models from different schemas inside the same database? 

I have a database called 'transform' and under that database I have a schema called 'public' and another called 'schema2'. This module seems to select which ever is designated as the default schema, which is 'public' in my case. How can select 'schema2'?

**Comment by durango** [comment]
You can now declare specific schemas, however you can only do one schema at a time. I would specify a different output directory for each schema then just do a `require-all` type of thing.
