### ISSUE TITLE
Does not works with indexes

### ISSUE THREAD

**Issue by ilya1st** [sequelize/sequelize-auto#162]
No indexes in generated models.
That's bad.

mysql> select @@version;
+-------------------------+
| @@version               |
+-------------------------+
| 5.6.28-0ubuntu0.15.10.1 |
+-------------------------+
1 row in set (0,00 sec)

nodejs -v
v7.10.0

brainstorm@brainstorm3:~/work/deshevie-bilety/cheaphotels$ ./node_modules/.bin/sequelize -version

Sequelize [Node: 7.10.0, CLI: 2.7.0, ORM: 3.30.2]

CLI version 3.9.1

**Comment by FredLackeyOfficial** [comment]
Am I missing something?  The README.md says nothing about indexes (no switch to enable or disable indexes).  Why, in the world, would anyone generate code, to sync or create their models, and NOT include indexes?

**Comment by Rukeith** [comment]
Schema didn't generate with index. That is wired.

**Comment by steveschmitt** [comment]
Indexes added in release 0.6.6.
