### ISSUE TITLE
How can you specify what schema to export from?

### ISSUE THREAD

**Issue by csaloio** [sequelize/sequelize-auto#17]
In a Postgres database export happens on the public schema. How can you specify a different schema to export from?

**Comment by jprempeh** [comment]
+1

**Comment by JasonMore** [comment]
I tried working on this a little bit, however I couldn't get sequelize to filter the schema down correctly. I probably need to file a bug with them. The sql below doesn't properly filter out all the columns from both of the tables

https://github.com/JasonMore/sequelize-auto

```
SELECT c.COLUMN_NAME AS 'Name',
 c.DATA_TYPE AS 'Type', 
 c.IS_NULLABLE as 'IsNull', 
 COLUMN_DEFAULT AS 'Default', 
 tc.CONSTRAINT_TYPE AS 'Constraint' 
 FROM INFORMATION_SCHEMA.TABLES t 
 INNER JOIN INFORMATION_SCHEMA.COLUMNS c 
 ON t.TABLE_NAME = c.TABLE_NAME 
 LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE cu 
 ON t.TABLE_NAME = cu.TABLE_NAME 
 AND cu.COLUMN_NAME = c.COLUMN_NAME 
 LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
  ON t.TABLE_NAME = tc.TABLE_NAME
   AND cu.COLUMN_NAME = c.COLUMN_NAME 
   AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY' 
   WHERE t.TABLE_NAME = 'Activity'
   AND t.TABLE_SCHEMA ='Staging'
```

**Comment by durango** [comment]
You can now define a schema through a config file and passing that file with the `-c` option
