### ISSUE TITLE
Socket Path

### ISSUE THREAD

**Issue by EgorZotov** [sequelize/sequelize-auto#173]
Hello I want to use sequelize-auto programmatic API and I cant connect through .
I need to use socket path  but i cant figure out how to pass it. I tried this already:
`var auto = new SequelizeAuto({
dialectOptions: {
        socketPath: '/var/run/mysqld/mysqld.sock'
    }});`

`var auto = new SequelizeAuto({
        socketPath: '/var/run/mysqld/mysqld.sock'
    });`

``var auto = new SequelizeAuto({
config: {
        socketPath: '/var/run/mysqld/mysqld.sock'
    }});``

``var auto = new SequelizeAuto({
config: {
        dialectOptions: {
        socketPath: '/var/run/mysqld/mysqld.sock'
    }
    }});``

**Comment by blimp666** [comment]
I have the same issue. I can use Sequelize in this way:

```
const sequelize = new Sequelize({
    database: 'dbname',
    host: '/var/run/postgresql',   
    dialect: 'postgres',
    dialectOptions: {
	socketPath: '/var/run/postgresql/.s.PGSQL.5433',
	supportBigNumbers: true,
	bigNumberStrings: true
    }
});
```
and it works perfect. But I can't find a way to use the same configuration with SequelizeAuto. Is it ever possible to use SequelizeAuto (or sequelize-auto executable file) with a unix socket connection ?

**Comment by steveschmitt** [comment]
Should be 

    var auto = new SequelizeAuto(database, username, password, { dialectOptions: { socketPath: '/var/run/mysqld/mysqld.sock' }});
