### ISSUE TITLE
Upgrade sequelize dependency to v4.x

### ISSUE THREAD

**Issue by sjfkai** [sequelize/sequelize-auto#180]
Could we Upgrade sequelize dependency to v4.x?

Because for mysql. It depend on `mysql2` for v4.x but `mysql` for now (v3.x). 

If we want to use `sequelize v4.x` and `sequelize-auto` we should install both `mysql2` and `mysql`.

**Comment by ShaunParsons** [comment]
:+1: is there a reason why this should not be done? Happy to open a PR for it, but is there any potential issues I should be aware of?

**Comment by chj-damon** [comment]
I'm using both sequelize and sequelize-auto in my project, but the version of sequelize is v4, but sequelize-auto still dependent on sequelize v3, So it would be great if sequelize-auto has a version that supports sequelize v4.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.0`
