### ISSUE TITLE
Generated attributes with spaces should be wrapped in quotes

### ISSUE THREAD

**Issue by LukeGeneva** [sequelize/sequelize-auto#182]
Table columns with spaces in their names cause syntax errors in the created models. For example, consider the following table:

### Users
- column1
- column2
- column 3

Currently this generates something similar to:
```
/* jshint indent: 2 */

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Users', {
    id: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    column1: {
      type: DataTypes.STRING,
      allowNull: true
    },
    column2: {
      type: DataTypes.STRING,
      allowNull: true
    },
    column 3: {
      type: DataTypes.STRING,
      allowNull: true
    },...
```

Column 3 is causing a syntax error in the attribute definition because of the space. This could be remedied by wrapping attributes with quotes if they contain spaces.
```
"column 3": {
  type: DataTypes.STRING,
  allowNull: true
},...
```
I've searched for this issue, but haven't found anything. If I've missed a configuration setting, please forgive me. 😃

**Comment by AshhWu** [comment]
Column names start with number will also cause syntax errors in the created models.
```
2in1: {
    type: DataTypes.STRING,
    allowNull: true
}
```
This could be remedied by wrapping attributes with quotes.
```
"2in1": {
    type: DataTypes.STRING,
    allowNull: true
}
```

**Comment by jtan25** [comment]
Was this issue ever resolved?
