### ISSUE TITLE
-- typescript or -z does nothing

### ISSUE THREAD

**Issue by AskYous** [sequelize/sequelize-auto#183]
Hello. I'm running this on Windows 10. I ran the following command but I was only given JS files. Am I doing something wrong?

`sequelize-auto -o "./models" -d <my-db> -h <my-host> -u <my-user> -p 5432 -x <my-password> -e postgres -z`

**Comment by AskYous** [comment]
Actually, looking at the available command line options, there's no support for TypeScript. But I see it in this repository's README file:

![image](https://user-images.githubusercontent.com/791996/29737289-00b04400-89c0-11e7-9452-607e02642a6f.png)

![image](https://user-images.githubusercontent.com/791996/29737327-70d0aa90-89c0-11e7-8188-17949bbbfc8a.png)

**Comment by AskYous** [comment]
The issue is that sequelize-auto on npm is not up to date.

**Comment by steveschmitt** [comment]
In `sequelize-auto@0.5.0`, the `-z` option was removed in favor of `-l` (lang).
