### ISSUE TITLE
TypeError: connection.query(...).on is not a function

### ISSUE THREAD

**Issue by jacyzin** [sequelize/sequelize-auto#184]
Hi, I found this error while generate models:
TypeError: connection.query(...).on is not a function
    at ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:156:31
    at Promise._execute  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:79:10)
    at ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:155:12
    at PassThroughHandlerContext.finallyHandler  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues  ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues ....\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

 I run this:
sequelize-auto -o "./models" -d DB -h xxx.xxx.xxx.xxx -u **** -p 5432 -x **** -e postgres

Can help?

**Comment by AskYous** [comment]
Hi. Check this: https://github.com/sequelize/sequelize/issues/7977#issuecomment-316421423

**Comment by bruno-serfe** [comment]
Hi Guys I've this error but it does not fixed with  updating version of pg to 6.4.1.... also I've current 7.4.0

this is a fragment of the error:

`TypeError: connection.query(...).on is not a function
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:156:31
`
I hope something knows the fix for this issue

**Comment by stonedraider** [comment]
same issues for me...

**Comment by NishantKhandelwal1** [comment]
Downgrade to pg@6.4.2 globally (`npm install -g pg@6.4.2`). It will solve your problem

**Comment by perriea** [comment]
No solution available ? ...

**Comment by dasimandl** [comment]
I had the same error and I just wanted to mention that, as stated by @NishantKhandelwal1, downgrading to pg@6.4.2 worked for me.

**Comment by SathishRaju** [comment]
Is this still not fixed for pg@7.x.x ?

**Comment by mk48** [comment]
still having the issue.... no fix yet.. :(

**Comment by Maxpain177** [comment]
+1

**Comment by bobberkarl** [comment]
Any fix yet?

**Comment by juberjj** [comment]
Not yet fixed but downgrading pg@6.4.2 it is a valid workaround.

**Comment by abdullah2993** [comment]
+1

**Comment by codemandavid** [comment]
downgrading doesn't work for me

**Comment by hazriqpedia** [comment]
This is working for me:

`npm install -g pg@6.1.5 pg-hstore@2.3.2 # Postgres`

Thanks guys!

**Comment by steveschmitt** [comment]
Hope you can continue with the workaround for now.  I hope to have a fix for this out soon.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.0`
