### ISSUE TITLE
Sequelize-auto not working

### ISSUE THREAD

**Issue by PandavaCharan** [sequelize/sequelize-auto#189]
I tried your code and facing an issue “ sequelize-auto command not found” .
Can someone help me how to resolve this.

npm install -g sequelize-auto

used global flag

Thanks,
Charan.

**Comment by rafdompa** [comment]
make sure that you're using sudo

**Comment by steveschmitt** [comment]
Try

    node node_modules/sequelize-auto/bin/sequelize-auto.js
