### ISSUE TITLE
Comment with quotes or special chars break the generated model

### ISSUE THREAD

**Issue by gorija** [sequelize/sequelize-auto#190]
Tried to connect to a gigantic corporate mysql base

"node ./node_modules/we-sequelize-auto/bin/we-sequelize-auto -o ./sequelize/auto -d database-name -h ip -u user -p 3306 -x ssssssh -e mysql"

sucessfull created 900+ table schema files.  But, some things are breaking the posterior .import

a) comments with quotes:   ""I"nternal, "E"xternal or  "B"oth"
b) special char from my native language, like [é] 
  
And, no, cleaning offensive characters on the corporate base is not a viable option. Politically, in the case.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.2`
