### ISSUE TITLE
sequelize deprecated String based operators are now deprecated.

### ISSUE THREAD

**Issue by AskYous** [sequelize/sequelize-auto#195]
I ran sequelize auto from my database. When I tried to use my models after they were generated, I received the following error:

`Fri, 10 Nov 2017 20:04:20 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules\sequelize\lib\sequelize.js:236:13`

Here's a screenshot during my debugging from VSCode:

![image](https://user-images.githubusercontent.com/791996/32676497-b64be3f6-c60f-11e7-9ab7-d8a0dd5a6d29.png)

**Comment by steveschmitt** [comment]
Was dependent upon an old version of `sequelize`.

Fixed in `sequelize-auto@0.5.1`.
