### ISSUE TITLE
column name "c.udt_name" not found

### ISSUE THREAD

**Issue by cwryjs** [sequelize/sequelize-auto#197]
I'm trying to generate models for an existing CockroachDB database (PostgreSQL).
sequelize-auto is performing a bunch of queries many of which error with `error: column name "c.udt_name" not found`

So I either did something horribly wrong or that column isn't supposed to exist on CockroachDB.

Does anyone have an idea why this might be the case or how I could fix it?

**Comment by thomasjm** [comment]
I'm seeing this too, it seems like CockroachDB doesn't have the `columns` view that PostgreSQL has. Here's the documentation on the view: https://www.postgresql.org/docs/8.0/static/infoschema-columns.html.

Were you able to find a solution?

**Comment by steveschmitt** [comment]
Is this still a problem in `sequelize-auto@0.5.1`?

**Comment by steveschmitt** [comment]
Fixed in sequelize-auto@0.5.1
