### ISSUE TITLE
Error: The dialect mssql is not supported.

### ISSUE THREAD

**Issue by aireater** [sequelize/sequelize-auto#20]
When I run the following command

```
sequelize-auto -h [server] -d [db name] -u [username] -x [pwd]   -e mssql -o './models'
```

I get the following error: 
/Users/this-guy/.nvm/versions/io.js/v2.0.1/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/sequelize.js:125
      throw new Error("The dialect " + this.getDialect() + " is not supported.
            ^
Error: The dialect mssql is not supported.

I'm trying to connect to a azure db if that makes a difference.

**Comment by ianseyer** [comment]
Are you trying to connect to a mysql database?

Not sure what mssql is.

**Comment by brettveenstra** [comment]
see https://github.com/sequelize/sequelize-auto/issues/12

**Comment by diegomesata** [comment]
Hello, I installed the mysql driver, that fix the error.

npm install -g mysql

**Comment by diegomesata** [comment]
npm install -g mssql
npm install -g tedious

**Comment by vinaybedre** [comment]
this have helped me to solve the issue. this issue can be set to close

**Comment by durango** [comment]
Closing this ticket and added additional comments in the README for MSSQL etc.
