### ISSUE TITLE
field max length

### ISSUE THREAD

**Issue by FranSancho** [sequelize/sequelize-auto#201]
At the moment i have something like:

    recordtype: {
      type: DataTypes.STRING,
      allowNull: true
    },

I would like to have something like:

    recordtype: {
      type: DataTypes.STRING,
      allowNull: true,
      maxLength: 10
    },

how could that be done?

**Comment by steveschmitt** [comment]
In `sequelize-auto@0.5.1`, it is

    type: DataTypes.STRING(10)

which matches the sequelize syntax.
