### ISSUE TITLE
unique:true needs to be changed to use string on export

### ISSUE THREAD

**Issue by x11joe** [sequelize/sequelize-auto#205]
https://github.com/sequelize/sequelize/issues/6134

refer to this issue, making a string name fixes the issue, otherwise duplicate indexes start appearing after every sync

**Comment by x11joe** [comment]
This is a deal breaker for me so I will be creating a fork of the project to fix the issue and will post it here.  I hope you decide to pull the code changes in the main version.

**Comment by steveschmitt** [comment]
This seemed to be a bug in `sequelize`, and was fixed in [PR 9033](https://github.com/sequelize/sequelize/pull/9033).
