### ISSUE TITLE
Last column in unique constraint incorrectly flagged as primary key

### ISSUE THREAD

**Issue by FredLackeyOfficial** [sequelize/sequelize-auto#208]
(Note: This ticket replaces #200 where it was believed only dates were affected.  It appears to be related to the unique constraint and *not* the data type.)

The last column within a unique constraint is being incorrectly flagged as `primaryKey: true` when generating models.

Example Index **without** constraint:

    CREATE INDEX uidx_profile_0
        ON authentication.profile USING btree
        (provider_id COLLATE pg_catalog."default", identifier COLLATE pg_catalog."default")
        TABLESPACE pg_default;

Resulting Model **without** constraint:

    /* jshint indent: 2 */

    module.exports = function(sequelize, DataTypes) {
      return sequelize.define('profile', {
        id: {
          type: DataTypes.BIGINT,
          allowNull: false,
          defaultValue: 'nextval(authentication.seq_profile::regclass)',
          primaryKey: true
        },
        provider_id: {
          type: DataTypes.CHAR,
          allowNull: false,
          references: {
            model: 'provider',
            key: 'id'
          }
        },
        identifier: {
          type: DataTypes.STRING,
          allowNull: false
        }
      }, {
        tableName: 'profile'
      });
    };

Next, we **remove** the index and add a **unique constraint**:  

    ALTER TABLE authentication.profile
        ADD CONSTRAINT uidx_profile_0 UNIQUE (provider_id, identifier);

The **last column** within the constraint is now flagged incorrectly:

    /* jshint indent: 2 */

    module.exports = function(sequelize, DataTypes) {
      return sequelize.define('profile', {
        id: {
          type: DataTypes.BIGINT,
          allowNull: false,
          defaultValue: 'nextval(authentication.seq_profile::regclass)',
          primaryKey: true
        },
        provider_id: {
          type: DataTypes.CHAR,
          allowNull: false,
          references: {
            model: 'provider',
            key: 'id'
          },
          unique: true
        },
        identifier: {
          type: DataTypes.STRING,
          allowNull: false,
          primaryKey: true
        }
      }, {
        tableName: 'profile'
      });
    };

And, to verify, let us check the DDL for the table:

	CREATE TABLE authentication.profile
	(
	    id bigint NOT NULL DEFAULT nextval('authentication.seq_profile'::regclass),
	    provider_id character(1) COLLATE pg_catalog."default" NOT NULL,
	    identifier character varying(255) COLLATE pg_catalog."default" NOT NULL,
	    CONSTRAINT pk_profile_id PRIMARY KEY (id),
	    CONSTRAINT uidx_profile_0 UNIQUE (provider_id, identifier),
	    CONSTRAINT fk_profile_provider FOREIGN KEY (provider_id)
	        REFERENCES authentication.provider (id) MATCH SIMPLE
	        ON UPDATE NO ACTION
	        ON DELETE NO ACTION
	)
	WITH (
	    OIDS = FALSE
	)
	TABLESPACE pg_default;

	ALTER TABLE authentication.profile
	    OWNER to postgres;

	-- Index: idx_profile_provider_id

	-- DROP INDEX authentication.idx_profile_provider_id;

	CREATE INDEX idx_profile_provider_id
	    ON authentication.profile USING btree
	    (provider_id COLLATE pg_catalog."default")
	    TABLESPACE pg_default;

**Comment by steveschmitt** [comment]
Fixed in 0.6.1
