### ISSUE TITLE
Unhandled rejection TypeError: undefined is not a function : lib\index.js:100:59 mssql dialect

### ISSUE THREAD

**Issue by brettveenstra** [sequelize/sequelize-auto#21]
Received this error when attempting to run against 'mssql' dialect (see hack in #12)

    Unhandled rejection TypeError: undefined is not a function
        at .....\node_modules\sequelize-auto\lib\index.js:100:59
        at Array.forEach (native)
        at .....\node_modules\sequelize-auto\lib\index.js:77:25
        at Array.forEach (native)
        at .....\node_modules\sequelize-auto\lib\index.js:63:18
        at .....\node_modules\sequelize-auto\node_modules\async\lib\async.js:187:20
        at .....\node_modules\sequelize-auto\node_modules\async\lib\async.js:239:13
        at _arrayEach (.....\node_modules\sequelize-auto\node_modules\async\lib\async.js:91:13)
        at _each (.....\node_modules\sequelize-auto\node_modules\async\lib\async.js:82:13)

        at Object.async.forEachOf.async.eachOf (.....\node_modules\sequelize-auto\node_modules\async\lib\async.js:238:9)
        at Object.async.forEach.async.each (.....\node_modules\sequelize-auto\node_modules\async\lib\async.js:215:22)
        at .....\node_modules\sequelize-auto\lib\index.js:51:15
        at .....\node_modules\sequelize-auto\node_modules\async\lib\async.js:52:16
        at done (.....\node_modules\sequelize-auto\node_modules\async\lib\async.js:248:21)

        at .....\node_modules\sequelize-auto\node_modules\async\lib\async.js:44:16
        at .....\node_modules\sequelize-auto\lib\index.js:47:13

**Comment by brettveenstra** [comment]
This looks to work but haven't run any tests other than against a single MSSQL DB

    var typeName = new String(_tables[table][field][attr]); 
    var _attr = typeName.toLowerCase(),
      val = "'" + typeName + "'";

**Comment by diegomesata** [comment]
@brettveenstra  That fix worked for me

**Comment by edision** [comment]
@brettveenstra That fix worked for me too.

**Comment by riemannzeta** [comment]
Thanks so @brettveenstra That worked for me also.  For any other n00bs interested, the fix goes into ./lib/index.js around line 100.  Sub those three lines in for the existing var attr_ declaration

**Comment by durango** [comment]
This is fixed within another PR. Thanks for the report and fix!
