### ISSUE TITLE
Issue with MSSQL

### ISSUE THREAD

**Issue by pvijaysimha** [sequelize/sequelize-auto#210]
can connect to mysql , problem is with MSSQL 2005.

$ sequelize-auto -o "../model" -d mydb -h 192.168.0.7 -u sa -p 1433 -x 123456 -e mssql 
/home/vj/.nvm/versions/node/v7.7.1/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:21
      throw new Error('Please install tedious package manually');
      ^

**Comment by beardedpayton** [comment]
Try installing it globally.

npm install -g tedious

**Comment by pvijaysimha** [comment]
Thanks, it worked.
