### ISSUE TITLE
Mysql not supported 

### ISSUE THREAD

**Issue by soufyaneMahjoubi** [sequelize/sequelize-auto#212]
Hello,

I Have this error when i try to start the programme :
- Error: The dialect true,mysql is not supported

i try : npm install -g mysql

but nothing works

**Comment by Miorey** [comment]
same for me 
Error: The dialect true,mysql is not supported

**Comment by steveschmitt** [comment]
I think this is fixed in `sequelize-auto@0.5.0`

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`.
