### ISSUE TITLE
hasTrigger is not detected

### ISSUE THREAD

**Issue by leolorenzoluis** [sequelize/sequelize-auto#217]
When using sequelize-auto, it doesn't detect if the table has trigger thus not generating `hasTrigger` flag and causing bulk inserts issues.

**Comment by joaoe** [comment]
Bump. This happens with Microsoft SQL at least. Quite a serious issue. Breaks Sequelize entirely when triggers are used.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`.
