### ISSUE TITLE
Auto generate primaryKey and autoIncrement

### ISSUE THREAD

**Issue by ht10vn** [sequelize/sequelize-auto#22]
Dear All,

I have used sequelize-auto to auto generate data model with DB MySQL. And the lib generate well.
But It is not auto generate primaryKey and autoIncrement for primary key field in DB.
Could anyone help me config to auto gen these field.

Thanks so much.

**Comment by ianseyer** [comment]
An interest side effect of this problem is that it renders sequelize completely unusable.

https://github.com/sequelize/sequelize/issues/4400

**Comment by ht10vn** [comment]
Thanks ianseyer,

I still have to used primary key, and autoincrement when calling create() object in sequenlize. If there are not pk, and autoincrement, it will not insert data to DB. (I am using Node V0,12, MySQL, and method create() as yours 4400)

**Comment by Name-less** [comment]
someone succeed to fix this issue ?

**Comment by durango** [comment]
If someone could provide a gist for me on the issue I'd be more than willing to take a look into it

**Comment by ht10vn** [comment]
I have to add primaryKey by manual.

**Comment by geolyth** [comment]
Now it seems to work...for me...

**Comment by durango** [comment]
Should be fixed now, let me know if you run into any issues (just tested on a local MySQL and Postgres instance). If you do run into any problems, please attach the generated file/example of the schema would help too. Hopefully that wont be the case though.
