### ISSUE TITLE
defaultValue for Boolean type is '0'(string) instead of false or at least 0 (Number)

### ISSUE THREAD

**Issue by vidyadharbusam** [sequelize/sequelize-auto#225]
"sequelize-auto": "0.4.28"
For a column in Mysql table, the model generated by sequelize-auto is like this 
`isattached: {
      type: DataTypes.INTEGER(1),
      allowNull: true,
      defaultValue: '0',
    },`
When ever, I use `findOrCreate`, it returns `'0'` in isattached field which not boolean value.

**Comment by vinnitu** [comment]
after object created default value is true because '0' is not false

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.2`
