### ISSUE TITLE
"," present when allowNull is the last option

### ISSUE THREAD

**Issue by Name-less** [sequelize/sequelize-auto#23]
When i generate my models and that allowNull is the last option, there is a "," before the end of the JSON : 

        cmd_value: {
      type: 'DOUBLE(14,4)',
      allowNull: false,
      defaultValue: '0.0000' //options generated perfectly
    },
    cmd_id: {
      type: DataTypes.BIGINT,
      allowNull: false, // , has nothing to do here ...
    }

Thanks for this answone lib !

**Comment by durango** [comment]
Closed, thanks for reporting the issue :+1:
