### ISSUE TITLE
TypeError: connection.query(...).on is not a function

### ISSUE THREAD

**Issue by joyguy55** [sequelize/sequelize-auto#234]
This I believe is a bug related to https://github.com/sequelize/sequelize/issues/7977 would be great if there was a quickish work around otherwise I might have to look at different library if there is one.

<img width="1227" alt="screen shot 2018-06-25 at 3 05 32 pm" src="https://user-images.githubusercontent.com/14304220/41878274-44b3bc50-7889-11e8-8651-f7bdc31839bf.png">

**Comment by klaaz0r** [comment]
After some looking around what did the trick for me was downgrading pg

`npm install -g pg@6` 

I was running a version 7+ with version 6 it is working for me

**Comment by jberall** [comment]
Thanks that worked for me!

**Comment by tadman** [comment]
The `-g` flag here is key. With `sequelize-cli` the `package.json` file isn't used.

**Comment by ziali088** [comment]
Also ran into this issue

**Comment by jomendoz** [comment]
Same, I got this issue also.

**Comment by lraulin** [comment]
Almost a year later, still getting a crash with TypeError while following the quick-start instructions in the documentation.  (sequelize-auto v0.4.29, pg v7.8.0)  I take it this project is abandoned.

**Comment by createthis** [comment]
I'm not sure it has been abandoned, given that it's still under the `github.com/sequelize` project. It has certainly been neglected though. 30 PRs outstanding at this point, one of mine among them.

**Comment by tadman** [comment]
As it stands this is incompatible with pg7+ so you'll need to hold back to 6 for now. Anyone volunteering to update?

**Comment by Cauen** [comment]
https://github.com/sequelize/sequelize-auto/issues/385

Downgrade to 6.15 and change the code of the lib.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.0`
