### ISSUE TITLE
ES6 Syntax Support

### ISSUE THREAD

**Issue by achillesrasquinha** [sequelize/sequelize-auto#240]
Would it be possible to consider ES6 Syntax support for model files generated?

**Comment by R4meau** [comment]
Looking forward to this too. I'm currently using [esm](https://github.com/standard-things/esm) in my codebase and I would really like to have my generated models use import/export statements too.

**Comment by steveschmitt** [comment]
Added in `sequelize-auto@0.5.0` 

You need to use the command line arguments `-l esm` to get ES modules.
