### ISSUE TITLE
TypeError: Path must be a string. 

### ISSUE THREAD

**Issue by joggerjoel** [sequelize/sequelize-auto#241]
I'm getting a similar error with ubuntu 18.04

npm install -g sequelize-auto
npm install -g sequelize
npm install -g mysql

sequelize-auto -o "./models" -h localhost -d dev_v400 -u root -x 123456 -dialect mysql

path.js:28
throw new TypeError('Path must be a string. Received ' + inspect(path));
^

TypeError: Path must be a string. Received [ true, true ]
at assertPath (path.js:28:11)
(/usr/local/lib/node_modules/sequelize-auto/bin/sequelize-auto:53:29)
at bootstrap_node.js:609:3

**Comment by joggerjoel** [comment]
https://github.com/sequelize/sequelize-auto/issues/213

I fixed this as well by forcing the two lines:
if (argv.c) {
  configFile = '/'; //require(path.resolve(argv.c));
}

if (argv.a) {
  additional = ''; //require(path.resolve(argv.a));
}

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.3`
