### ISSUE TITLE
Auto generated model keeps the old column after the old column was renamed in the database table

### ISSUE THREAD

**Issue by SCCGit** [sequelize/sequelize-auto#245]
Here is the change made in the MSSQL database. A column in a table was renamed from A to B.
The model was regenerated using sequelize-auto. The new generated model has both column A (old) and column B(new). Let me know if there is anything I should do in sequelize auto script to fix this.

var auto = new SequelizeAuto(dbConfig.db, dbConfig.user, dbConfig.password, {
      host: dbConfig.host,
      dialect: dbConfig.dialect,
      operatorsAliases: false,
      port: dbConfig.port,
      dialectOptions: dbConfig.dialectOptions,
      directory: modelPath,
      logging : dbConfig.logging,
      database: dbConfig.db,
      additional: {
        timestamps: false,
        schema: 'Shopping'
      },
     tables: ['BuyerCode' ]
    })

  auto.run(function (err) {
    if (err) throw err;
  
  });

**Comment by steveschmitt** [comment]
Is this still a problem in `sequelize-auto@0.5.1`?

**Comment by steveschmitt** [comment]
Unable to reproduce this issue.
