### ISSUE TITLE
Columns for foreign key are tagged as primary key

### ISSUE THREAD

**Issue by TitaneBoy** [sequelize/sequelize-auto#29]
Hi.. I used your great module and I noticed that columns which are part of foreign key are tagged as "primary key", but they should be tagged as "references: {model: 'ModelName', key: 'keyName'}. I'm using PostgreSQL database and inside this database, these columns are part of foreign key.

It will be great to correct that issue if possible.

Thank you very much

**Comment by AykutBurak** [comment]
Why is this issue closed? Any solutions? 3 years later and I'm still having the same issue.
