### ISSUE TITLE
How to run sequelize-auto in windows?

### ISSUE THREAD

**Issue by explorer2309** [sequelize/sequelize-auto#3]
Hi,

Is this module supposed to work on windows?
I am unable to do it so far.

Thanks!

**Comment by guru-apr21** [comment]
Now it is possible to run sequelize auto from the root folder of your project using npx.
```console
npx sequelize-auto -o "../../../models" -d amazon -h localhost -u root -p 3306 -x pass -e mysql --cm p --cf p -l es6 --sg
```
