### ISSUE TITLE
id autoIncrement is not set while generating models from mysql db

### ISSUE THREAD

**Issue by eighteight** [sequelize/sequelize-auto#31]
I have a mysql db, and generate the models like so:
```
$ sequelize-auto -o "./models" -d MY_DATABASE -h localhost -u USERNAME -p 3306 -x USERPASSWORD -e mysql

```

For the id table fields, which are set to AUTOINCREMENT in the mysql database, the sequelize-auto does not provide the autoincrement descriptor, and subsequently the insert operation generates SequelizeValidationError.

If I add autoincrement by hand, however, like so:

```
id: {
      type: DataTypes.INTEGER(10),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
```

Everything works.

**Comment by vtech-yash** [comment]
Yes faced the same issue

**Comment by durango** [comment]
Will take a look at it on Monday or so after work

**Comment by durango** [comment]
@eighteight could you provide a schema dump for your database? Or just the table that's giving you issues at least. This way I can diagnose a bit better.

**Comment by kobleistvan** [comment]
Hi there, I approve, I have the same issue too. Made the schema in workbench, set PK, NN and AI. Generator omits the autoIncrement attribute.

**Comment by CodTicker** [comment]
Issue remains:

Myql table: 

```
CREATE TABLE `languages` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Language` varchar(45) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

Generating models: 

`sequelize-auto -h 127.0.0.1 -d DBNAME -u root -x PASSWORD -p 3306 --dialect mysql -c MYPATH\json/sequelize-auto-settings.json -o MODELSPATH\src\assets\models`

Result: 

```
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('languages', {
        Id: {
            type: DataTypes.INTEGER(11),
            allowNull: false,
            primaryKey: true,
            field: 'Id'
        },
        Language: {
            type: DataTypes.STRING(45),
            allowNull: false,
            field: 'Language'
        }
    }, {
        tableName: 'languages'
    });
};
```
