### ISSUE TITLE
DOUBLE is not suported?

### ISSUE THREAD

**Issue by wen911119** [sequelize/sequelize-auto#337]
![image](https://user-images.githubusercontent.com/13494648/50340987-1b9c4d80-0558-11e9-83be-4eaf64242f5f.png)

**Comment by wen911119** [comment]
https://github.com/sequelize/sequelize-auto/blob/c16e8c0b5b977372be0209bde1bd22c920538065/lib/index.js#L327
I `console.log()` the data type of the fields in my project and then find the type name of "DOUBLE" is 'double', not the 'double precision'. maybe we should change the line into 
`else if (_attr.match(/^(float8|double precision|double|numeric)/)) {` 
?

![image](https://user-images.githubusercontent.com/13494648/50390011-6c848f80-076c-11e9-91f3-cfcd88c2bdb6.png)

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.0`
