### ISSUE TITLE
mysql2 support

### ISSUE THREAD

**Issue by jjangga0214** [sequelize/sequelize-auto#341]
Currently it fully depends on *mysql* package. 
It'd be better if it works even if there is only *mysq2* installed.

**Comment by ALiangLiang** [comment]
Because this project still using Sequelize v3. Need to upgrade to Sequelize v4 or v5 first.

**Comment by jjangga0214** [comment]
@ALiangLiang Do you know whether there is a concrete plan?

**Comment by steveschmitt** [comment]
We just released  `sequelize-auto@0.5.1` which supports the latest `sequelize`
