### ISSUE TITLE
Project Being Maintained?

### ISSUE THREAD

**Issue by devspacenine** [sequelize/sequelize-auto#345]
Is this project still being maintained? Seems there are a lot of pull requests and issues that have not been addressed or don't even have a response.

**Comment by davidadas** [comment]
Yeah, I think they've moved on honestly.

**Comment by selected-pixel-jameson** [comment]
Would be really nice to get an answer on this at least. Having this is a huge time saver for me.

**Comment by 4umfreak** [comment]
Looked at the forks. It seems everyone and his dog has a fork of this for their own purposes - but none with any real improvements or commits. There's a few good fixes in PR's here that should be accepted...

**Comment by ALiangLiang** [comment]
@durango

**Comment by papb** [comment]
@sushantdhiman Do you have any info on this? Thanks :)

**Comment by tiagomsmagalhaes** [comment]
So this is pretty much dead?

**Comment by selected-pixel-jameson** [comment]
Ok. So based on lack of response does anyone know of a library that is similar but still maintained?

**Comment by martywins** [comment]
At the very least @durango should take the time to hand this over to a new
owner who is willing to maintain

**Comment by 4umfreak** [comment]
If you email him he'll reply, but I'd recommend you spend some time looking at it before you choose to step up. I started there and rewrote most of it for my own project ( https://github.com/transomjs/transom-sequelize ) because it's two major versions behind and the code needs some major cleanup.

**Comment by bburns** [comment]
> Ok. So based on lack of response does anyone know of a library that is similar but still maintained?

See the Sequelize docs for some alternatives - **sequelizer** worked for me - 

https://sequelize.org/master/manual/resources.html

Auto Code Generation & Scaffolding

- meteor modeler - Desktop tool for visual definition of Sequelize models and asssociations.
- sequelize-ui - Online tool for building models, relations and more.
- sequelizer - A GUI Desktop App for generating Sequelize models. Support for Mysql, Mariadb, Postgres, Sqlite, Mssql.
- sequelize-auto Generating models for SequelizeJS via the command line is another choice.
- pg-generator - Auto generate/scaffold Sequelize models for PostgreSQL database.
- sequelizejs-decorators decorators for composing sequelize models

**Comment by steveschmitt** [comment]
Sorry about the lack of response.  I've recently been added as a maintainer and am moving it forward.

Just released `sequelize-auto@0.5.1`, which supports latest `sequelize` and dialect libraries.
