### ISSUE TITLE
read password from console?

### ISSUE THREAD

**Issue by zypA13510** [sequelize/sequelize-auto#351]
Many CLI applications have the option to run with the password switch but without providing any value, and then prompts for the password with echo turned off (i.e. you cannot see the password on screen). For example:
```console
$ mysql -h host -P 3306 -u user -p
Enter password:
^C
$ mysql -h host -P 3306 -u user -p=password
mysql: [Warning] Using a password on the command line interface can be insecure.
```

This can prevent leaving the password in shell history e.g. `~/.bash_history`. But it seems like sequelize-auto does not support this at the moment?

**Comment by rainabba** [comment]
I would think the `read` command would be exactly what you want here. I'm using echo for clarity, but it's just a variable so passing to a command should be no more difficult.

`echo "What's the pass?"; read pass && echo "mysql -h host -P 3306 -u user -p=$pass"`

**Comment by zypA13510** [comment]
Thank you, it's better than leaving the password in the bash history. But it's still displayed on-screen. And it's more of a workaround than a solution.

But yeah, I know I shouldn't hope for too much since no one maintains this anymore.

**Comment by rainabba** [comment]
I've updated my comment. Use `read -s` to ensure the password can't be seen on screen as its typed.

**Comment by steveschmitt** [comment]
Is the `read -s` solution viable?  Or do we really need to build something into sequelize-auto?

**Comment by zypA13510** [comment]
@steveschmitt I guess you can say it satisfied my needs. However, I'd still suggest we have this built into sequelize-auto itself, because not every user is security-conscious and it is best that we make sure the best security practice is actually the easiest route any user would take, i.e. have this silent password prompt built-in like MySQL does. Maybe it's not so high-priority I guess.

But now you're here maintaining this again, I might actually look into this and build a PR.
