### ISSUE TITLE
An issue to detect auto increment key on the MySQL 8

### ISSUE THREAD

**Issue by jeongjuwon** [sequelize/sequelize-auto#352]
On the MySQL 8, the query below has column of execution result which named EXTRA. Because it is named uppercase, the logic can not detect the column the extra. So the query should has alias for that.

```sql
SELECT
    K.CONSTRAINT_NAME AS constraint_name,
    K.CONSTRAINT_SCHEMA AS source_schema,
    K.TABLE_SCHEMA AS source_table,
    K.COLUMN_NAME AS source_column,
    K.REFERENCED_TABLE_SCHEMA AS target_schema,
    K.REFERENCED_TABLE_NAME AS target_table,
    K.REFERENCED_COLUMN_NAME AS target_column,
    C.extra **as extra**,
    C.COLUMN_KEY AS column_key
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS K
        LEFT JOIN
    INFORMATION_SCHEMA.COLUMNS AS C ON C.TABLE_NAME = K.TABLE_NAME
        AND C.COLUMN_NAME = K.COLUMN_NAME
WHERE
    K.TABLE_NAME = 'asset'
        AND K.CONSTRAINT_SCHEMA = 'caredog';
```

[ before ]

| constraint_name | .... | EXTRA          | column_key |
| --------------- | ---- | -------------- | ---------- |
| PRIMARY         | .... | auto_increment | PRI        |
| asset_id_UNIQUE | .... | auto_increment | PRI        |

[ after ]

| constraint_name | .... | extra          | column_key |
| --------------- | ---- | -------------- | ---------- |
| PRIMARY         | .... | auto_increment | PRI        |
| asset_id_UNIQUE | .... | auto_increment | PRI        |

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.0`
