### ISSUE TITLE
`SequelizeAuto.run` generates models for VIEWS

### ISSUE THREAD

**Issue by joaoe** [sequelize/sequelize-auto#354]
Hi.

Context:
1. `SequelizeAuto` generates models for VIEWs and then `Sequelize.import` crashes due to lack of a primary key on the Id column. I got the reply there that `Sequelize` does not support VIEWs.
https://github.com/sequelize/sequelize/issues/10546
2. Someone else asked that VIEWs should be generated so it could be that support is inconsistent across databases. https://github.com/sequelize/sequelize-auto/issues/77

In my case I'm using Microsoft SQL. When `SequelizeAuto` runs, the very first query is:
```
SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES;
```

This is incomplete. There query should be
```
SELECT TABLE_NAME, TABLE_SCHEMA, TABLE_TYPE FROM INFORMATION_SCHEMA.TABLES;
-- or
SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE  != 'VIEW';
```

IF you want to generate models for views, then the models objects should be somehow marked as read-only or as views, unless it's a view with an insert, update or delete trigger. But that would be out of the scope of this issue report.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`

**Comment by psychodad71** [comment]
Views in postgres are still mising:

This SQL Statement 

_SELECT table_name FROM information_schema.tables WHERE table_schema = 'xa18_db2' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';_

has to be modified to:

_SELECT table_name FROM information_schema.tables WHERE table_schema = 'xa18_db2' AND (table_type LIKE '%TABLE' or table_type LIKE '%VIEW') AND table_name != 'spatial_ref_sys';_

**Comment by steveschmitt** [comment]
@psychodad71 The original issue says that models **are** generated for views, but they should **not** be.  Are you saying the opposite?

**Comment by joaoe** [comment]
The goal of the task is to NOT generate models for views, because obviously views are read only and Sequelize does not like that, e.g., lack of keys.
If Sequelize implements some sort of keyless+read-only model type, then view support could be reintroduced.
In my project at least, we had to explicitly delete the models for views after running sequelize auto.
