### ISSUE TITLE
Can you add model generics to FindOptions?

### ISSUE THREAD

**Issue by Vi-jay** [sequelize/sequelize-auto#366]
There is no model field hint in the ’where‘ field of FindOptions. It is very sad.

**Comment by steveschmitt** [comment]
With the 0.6.4 release, we have completely changed the way we generate TypeScript files.  Now it is more like the [TypeScript usage](https://sequelize.org/master/manual/typescript.html#usage) example in the Sequelize documentation.

The "db" file is now called `init-models.ts`.  There is a brief example of usage in the [README](https://github.com/sequelize/sequelize-auto/blob/master/README.md#typescript).

Please give it a try and let me know how it goes.

**Comment by steveschmitt** [comment]
I think this issue belongs in `sequelize/sequelize` instead of `sequelize-auto`.
