### ISSUE TITLE
Incorrect error handling

### ISSUE THREAD

**Issue by glebfeklistov** [sequelize/sequelize-auto#375]
Please replace this:
if (err) console.error(err)
To this:
if (err) throw err;
in lib/index.js

**Comment by glebfeklistov** [comment]
Or add error to callback in:
return callback(null, text);
And remove:
if (err) console.error(err)
in lib/index.js

**Comment by steveschmitt** [comment]
I think error reporting is done this way so that if a single model has an error, all the other models can still be generated.

**Comment by steveschmitt** [comment]
Issue obsolete due to code changes.
