### ISSUE TITLE
Key info lost if there are other constraints

### ISSUE THREAD

**Issue by joaoe** [sequelize/sequelize-auto#381]
Hi.
I have a case where a table self-references itself, to allow for recursive queries.
I'm using MS Sql Server.
A simple testcase:
```
CREATE TABLE HelloWorld(
  Id INTEGER IDENTITY PRIMARY KEY,
  NAME VARCHAR(40));
ALTER TABLE HelloWorld
  ADD OtherId INTEGER
  CONSTRAINT HelloWorld_FK FOREIGN KEY (OtherId) REFERENCES HelloWorld(Id),
  CONSTRAINT HelloWorld_CHK CHECK (OtherId <> Id);

INSERT INTO HelloWorld(Name) VALUES ('a');
INSERT INTO HelloWorld(Name, OtherId) VALUES ('a', 1);
SELECT * FROM HelloWorld;
```
When sequelize reads key information in `lib/index.js:mapForeignKeys()` it overwrites column information for each key it finds in a column as `self.foreignKeys[table][ref.source_column] = _.assign({}, self.foreignKeys[table][ref.source_column], ref);`.

The query that return FOREIGN KEY info in MS SQL comes from `lib/dialects/index.js:exports.<name>.getForeignKeysQuery`. That query will select all constraints, including CHECKs and those come after the KEY constraints, and as such will overwrite what came before. Unfortunately, then `c.is_identity` is set to `0` in the case of a `CHECK`.

Conclusion: because key info is lost, `autoIncrement` is never output, and the generated models fail to insert any rows in the database.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`
