### ISSUE TITLE
Getting error in this line `Cannot use namespace 'DataTypes' as a type.ts(2709)`

### ISSUE THREAD

**Issue by anjnkmr** [sequelize/sequelize-auto#384]
Line: https://github.com/sequelize/sequelize-auto/blob/c16e8c0b5b977372be0209bde1bd22c920538065/lib/ts-helper.js#L13

![Alt text](https://i.postimg.cc/m2xRTK17/error-in-generating-typescript-models.png?raw=true "Error")

I used the below configuration to generate models

```
const auto = new SequelizeAuto(
process.env.DB_NAME,
process.env.DB_USER,
process.env.DB_PASS,
{
  host: process.env.DB_HOST,
  dialect: 'mysql',
  typescript: true,
  camelCaseForFileName: true,
  directory: './src/data/entity'
})
auto.run();
```

**Comment by anjnkmr** [comment]
I forked and updated the repository as per my project requirements, https://github.com/realvariabledas/sequelize-auto

**Comment by anjnkmr** [comment]
There is a project specific class DI, instead of this class you can create object yourself to the Class name in parameters

**Comment by rtman** [comment]
for future reference, this works.

```
DataTypes: typeOf Sequelize.DataTypes
```
