### ISSUE TITLE
Looking for maintainers!!

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize-auto#398]
Hey Everyone,

This library is currently not maintained. Last release was over two years ago. Currently no one on Sequelize team is familiar with this code-base.

If you are using this library and/or want to improve it by taking care of issues, discussing new features and merging PRs, please let us know. You can comment here or contact me at `sushantdhiman@outlook.com`.

Thanks!

**Comment by steveschmitt** [comment]
Sure, why not?  Better than creating another fork!

I'm already a maintainer of [breeze](https://github.com/Breeze/breeze-client) and [breeze-sequelize](https://github.com/Breeze/breeze.server.node/tree/master/breeze-sequelize).  I don't know how much time I'll be able to devote to this, but I should be able to get things up-to-date.  I suppose the hard part will be getting databases set up to test it.

Let me know what I need to do.

**Comment by osmanraifgunes** [comment]
Please fork and continue. He is afk :)

**Comment by papb** [comment]
No, please don't fork and continue, we are not afk, we are overwhelmed with things.

**Comment by osmanraifgunes** [comment]
I would also love to contribute. I fixed a few bugs on my local repo. It is working on my local. It is not perfect but so so.

**Comment by papb** [comment]
Let me give a proper response now :grinning: Thank you @steveschmitt and @osmanraifgunes for being interested in helping!! We are currently overwhelmed with so many things to take care of. Sorry for not replying faster. I will see with @sushantdhiman what he is planning, and reply here as soon as possible.

**Comment by sushantdhiman** [comment]
Thanks for your interest @steveschmitt , I have added you to this repository.

We still don't have access to npm package, I'll try to reach out to old maintainer. I'll add you to npm once I have proper access.

Meanwhile you are free to improve repository, close issues & PR etc. Please reach out to me at `sushantdhiman@outlook.com` if you have any questions or concerns.

**Comment by steveschmitt** [comment]
Thanks!  I'll get started.

**Comment by puti94** [comment]
https://github.com/puti94/sequelize-auto
I fixed some bugs in the V5 version myself and added some new features.
But it changed a lot。

**Comment by steveschmitt** [comment]
Thanks @puti94 .  Can you create a pull request into this repo?  I probably won't merge it, but the PR will help me to see the bug fixes and features that you have added.
Thanks!

**Comment by puti94** [comment]
#404   @steveschmitt  You can see it here

**Comment by steveschmitt** [comment]
Thanks, I will look.

**Comment by steveschmitt** [comment]
@sushantdhiman Have you been able to get npm access?  I have many changes in place (in the `develop` branch), and I would like to be able to do a new release.

**Comment by sushantdhiman** [comment]
I have already invited you to the package a few days ago

![image](https://user-images.githubusercontent.com/9989487/86085312-7521f880-babc-11ea-876b-cf9a71c511e6.png)

**Comment by Tayflo** [comment]
There has been some forks already, like : 
- [nodejh/sequelize-automate](https://github.com/nodejh/sequelize-automate) ([on npm](https://www.npmjs.com/package/sequelize-automate)) (latest publication 2 months ago, seems pretty up to date)
- [naren7229/sequelize-auto-v3](https://github.com/naren7229/sequelize-auto-v3) ([on npm](https://www.npmjs.com/package/sequelize-auto-v3)) (latest publication 9 months ago)

I've just seen this after a quick search, I don't know if it could be helpful, maybe those guys could rather come maintain this original project.

**Comment by Tayflo** [comment]
There has been some forks already, like : 
- [nodejh/sequelize-automate](https://github.com/nodejh/sequelize-automate) ([on npm](https://www.npmjs.com/package/sequelize-automate)) (latest publication 2 months ago, seems pretty up to date)
- [naren7229/sequelize-auto-v3](https://github.com/naren7229/sequelize-auto-v3) ([on npm](https://www.npmjs.com/package/sequelize-auto-v3)) (latest publication 9 months ago)

I've just seen this after a quick search, I don't know if it could be helpful, maybe those guys could rather come maintain this original project.

**Comment by steveschmitt** [comment]
New release will be coming out this weekend.

**Comment by steveschmitt** [comment]
I've published version 0.5.0 under the **next** tag.  So 
```
npm install sequelize-auto@next 
```

will give you the new version.  See the [CHANGELOG](https://github.com/sequelize/sequelize-auto/blob/master/CHANGELOG.md) for a list of changes.

Please try it out and let me know if it works for you.  Then I'll publish it as **latest**.
Thanks!

**Comment by sushantdhiman** [comment]
Nice update @steveschmitt , I am closing this issue (and unpinning it).
