### ISSUE TITLE
The run method in version 0.5.2 is invalid

### ISSUE THREAD

**Issue by 1292150917** [sequelize/sequelize-auto#409]
同一份代码，我在0.4.29上面有效果，但是版本切换到0.5.2就失效了， 这段代码同样的版本失效
` var auto = new SequelizeAuto(jsoncurd.database, jsoncurd.user, jsoncurd.password, {
        host: jsoncurd.host,
        dialect: jsoncurd.type,
        directory: false,
        port: jsoncurd.port,
        additional: {
            timestamps: false
        },
        tables: name
    })
    await new Promise(s => {
        auto.run(async function (err) {
            if (err) throw err;
			console.log(auto.tables) // {}此处为空
            tables = auto.tables
            s(true)
        });
    })`

**Comment by 1292150917** [comment]
补充：在运行的时候会出一段：Executing (default): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'; 然后无具体运行效果

**Comment by 1292150917** [comment]
求解决~

**Comment by steveschmitt** [comment]
Yes, it seems that when you specify the `tables: ` option, it is excluding all tables!  I will fix.

**Comment by 1292150917** [comment]
不是的，我的tables是存在表的（动态赋值的data）。不然为何同份代码在 0.4.29就存在效果，而0.5.2就失效了呢？ 是改了什么用法么？

**Comment by 1292150917** [comment]
thank you

**Comment by 1292150917** [comment]
Looking forward to a quick fix, I have now reverted to version 0.4.29, but still not supported: autoIncrement:auto,Hope to solve it as soon as possible.

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.3`, just released.
