### ISSUE TITLE
 How do I put the first capital letter in the class?

### ISSUE THREAD

**Issue by osvaldokalvaitir** [sequelize/sequelize-auto#413]
I am using the script with `-l esm` and `-f ut`.

the `-f ut` works fine, would I have an UpperCamelCase in the class name only?

because if I use `-C ut` the field names will change too, but I just want the name of the class.

how to do that?

**Comment by steveschmitt** [comment]
Hmm.  I also think it would be better to UpperCamelCase only the class names.  That's a more standard JavaScript style.

**Comment by steveschmitt** [comment]
Fixed in 0.5.4.

Now there are separate options, `caseModel`, `caseFile`, and `caseProp` for controlling the cases of the model names, the file names, and the property names.  See the README.
