### ISSUE TITLE
Error: 'INTEGER' of undefined

### ISSUE THREAD

**Issue by osvaldokalvaitir** [sequelize/sequelize-auto#414]
I generated the models with `-l esm`:

`
/* jshint indent: 2 */

import { Model } from 'sequelize';

export default class customers extends Model {
  static init(sequelize, DataTypes) {
    super.init(
      {
        code: {
          type: DataTypes.INTEGER,
          allowNull: false,
          primaryKey: true,
        },
      },
      {
        sequelize,
        tableName: 'customers',
      }
    );
    return customers;
  }
}
`

but when running the following error occurred:

type: DataTypes.INTEGER,
                          ^
TypeError: Cannot read property 'INTEGER' of undefined

Did I do something wrong?

**Comment by steveschmitt** [comment]
How are you calling the `init` method?

**Comment by osvaldokalvaitir** [comment]
import Sequelize from 'sequelize';

import models from 'core/models';

import databaseConfig from '../config/database';

class Database {
  constructor() {
    this.init();
  }

  init() {
    this.connection = new Sequelize(databaseConfig);

    models
      .map(model => model.init(this.connection))
      .map(model => model.associate && model.associate(this.connection.models));
  }
}

export default new Database();

**Comment by steveschmitt** [comment]
Obviously, you need to use 

    .map(model => model.init(this.connection, DataTypes))

**Comment by osvaldokalvaitir** [comment]
thanks, Steve! It worked! ignore my pr that I did, please!
