### ISSUE TITLE
MSSQL Invalid queries when running on case-sensitive DB collation

### ISSUE THREAD

**Issue by karpikpl** [sequelize/sequelize-auto#416]
**Steps to reproduce**
1. run entity generation on MSQL with case-sensitive collation

```
DECLARE @sql NVARCHAR(100)
SET @sql='ALTER DATABASE ' + quotename(db_name()) + ' COLLATE SQL_Latin1_General_CP1_CS_AS';
EXEC(@sql)
GO

EXECUTE sp_helpsort;

Server default collation
Latin1-General, case-insensitive, accent-sensitive, kanatype-insensitive, width-insensitive for Unicode Data, SQL Server Sort Order 52 on Code Page 1252 for non-Unicode Data
```

**Expected**
DB entities generated

**Actual**
Failures with queries which point to lower-case (sometimes upercase) table names.

**Solution**
Changes in the library have to be applied in 3 places:
1. `INNER JOIN sys.COLUMNS` -> `INNER JOIN sys.columns`
2. `FROM information_schema.tables` -> `FROM INFORMATION_SCHEMA.TABLES`
3. `FROM information_schema.triggers` -> `FROM INFORMATION_SCHEMA.TRIGGERS`

I'll create a PR in few minutes

**Comment by steveschmitt** [comment]
Fixed in 0.5.4.  Thanks for the PR!
