### ISSUE TITLE
Why DROP ALL TABLES

### ISSUE THREAD

**Issue by ambrozihorn** [sequelize/sequelize-auto#418]
Why this code inside helper?

![image](https://user-images.githubusercontent.com/32131685/90565625-98dcf300-e17d-11ea-960a-ac659dab1a3d.png)

**Comment by steveschmitt** [comment]
It is used to clean up the test database when running the test suite.

**Comment by ambrozihorn** [comment]
Why? Why I need clear the database if i want exactly get the structure?
That is dangerous because, if you already have a database,it will drop the tables.

**Comment by steveschmitt** [comment]
This code is only used when running the tests.  The tests create the database, add some tables, generate some output, test the output, and drop the tables.  Sequelize-auto does not call `dropAllTables` in normal use.

Perhaps the right thing to do is remove all the test code from the shipping product (npm package).

**Comment by papb** [comment]
> Perhaps the right thing to do is remove all the test code from the shipping product (npm package).

@steveschmitt  Yeah, I agree, it's a good idea! By the way I noticed this repository uses `.npmignore` file, but that is Considered Harmful™, please remove it and use the [`"files": [<glob list here>]` package.json option](https://docs.npmjs.com/configuring-npm/package-json.html#files) instead.

Thank you so much for the great work :+1:

**Comment by steveschmitt** [comment]
Fixed in 0.5.4
