### ISSUE TITLE
Fix(MySQL) : Missing autoIncrement attribute in generated models

### ISSUE THREAD

**Issue by marcelopc** [sequelize/sequelize-auto#419]
Issue:
autoIncrement: true is missing on generated models.

Environment:
OS: Linux
MySQL: 8.0.11
node: v12.13.0
npm: v6.13.7
sequelize-auto: 0.5.3

Details:
During the generation, I realized that the autoIncrement was being removed so I started to notice that when you have several schemas with tables and columns of the same name but with different properties (the first one having autoIncrement and the second one not) the library goes through the schemas and makes the thus replacing the autoIncrement.

**Comment by steveschmitt** [comment]
Fixed in 0.5.4.  Thanks for the PR.
