### ISSUE TITLE
connect to db via Connection string

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize-auto#421]
Note added later: even better, since sequelize is required: using the programatic API can accept a sequelize instance, instead of db user/pass.

==

Most database providers give only the Connection string by default, eg
```
postgres://analyst:98kd8a9@ec2-123-73-145-214.compute-1.amazonaws.com:6212/dee932clc3mg8h
```
https://devcenter.heroku.com/articles/heroku-postgresql-credentials

Note this is one string, no need to specify the separate fields.

Would you please support connecting to DB using this Connection string?

`new SequelizeAuto(config)` could accept a single object parameter, with `connectionString` set as one of the properties, or a sequelize instance.

FYI https://github.com/brianc/node-postgres works with connectionString
here's how another JS project implemented it: https://github.com/beekeeper-studio/beekeeper-studio/issues/178

**Comment by mariusa** [comment]
@steveschmitt Steve, what do you think about being able to accept a sequelize instance instead of db user/pass?

That instance will be already connected via a Connection string

**Comment by steveschmitt** [comment]
That should already work, because you can pass a sequelize instance instead of database name as the first parameter to the SequelizeAuto constructor: 
```
var SequelizeAuto = require('sequelize-auto');
var myseq = // create sequelize instance;
var auto = new SequelizeAuto(myseq);
```

**Comment by mariusa** [comment]
Thanks! How can one also provide the options? I tried
```
var auto = new SequelizeAuto(myseq, options);
```
but this won't work

**Comment by steveschmitt** [comment]
I think you would need to use:
```
var auto = new SequelizeAuto(myseq, null, null, options); 
```

**Comment by mariusa** [comment]
that does work, thanks!

Shall I leave this open to be able to get rid of the nulls or simply use it like that and close this issue? (works for me)

**Comment by steveschmitt** [comment]
I think it is good enough.  I will update the README to demonstrate this use-case.  You may close the issue.
