### ISSUE TITLE
please consider removing eslint from package.json

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize-auto#425]
To minimize deps, please consider removing eslint from package.json

It seems it's used only when an eslint option is passed
https://github.com/sequelize/sequelize-auto/blob/58ece8d4d86b136847696a3ce0e928b8aec17267/lib/index.js#L597

but there's no such option in README
https://github.com/sequelize/sequelize-auto/search?q=eslint&unscoped_q=eslint

As an user of this project, I also don't see why eslint should be ran on generated models code. It works great without it.

Thanks!

**Comment by steveschmitt** [comment]
Fixed in 0.5.4 

Moved eslint to devDependencies and only call it during tests

**Comment by mariusa** [comment]
Thank you!
