### ISSUE TITLE
Postgres JSONB default value is inserted as string instead of JSONB

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize-auto#426]
## Issue Description
Have a table with JSONB default

```
CREATE TABLE charge(
    id TEXT NOT NULL PRIMARY KEY,
    title TEXT,
    tax_ids JSONB DEFAULT '[]'
);
```
Extract models with sequelize-auto, it gives

```
tax_ids: {
            type: DataTypes.JSONB,
            allowNull: true,
            defaultValue: "[]"
        },
```

### What are you doing?

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)

let charge = {
        id: '123'
}
await sequelize.charge.create(charge)
```

### What do you expect to happen?

tax_ids field wasn't specified, so in database it should end as JSONB with value `'[]'`

### What is actually happening?

sequelize inserts it as `'"[]"'`

Here's the difference:
```
select tax_ids from charge;
 tax_ids 
---------
 [] -- correct
 []
 "[]" -- wrong
```

### Environment

- Sequelize version: 6.3.4 
- Node.js version: 12 
- Operating System: linux

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

### More info

Fixing the model solves the issue:
```
        tax_ids: {
            type: DataTypes.JSONB,
            allowNull: true,
            defaultValue: []
        },

```

Another case where it shouldn't have quotes:

```
        tax_amount: {
            type: DataTypes.DOUBLE,
            allowNull: false,
            defaultValue: "0"
        },
```

So it's a sequelize-auto issue.

**Comment by mariusa** [comment]
Hi @steveschmitt 

I see the same issue for DataTypes.DOUBLE, numbers are in quotes. Maybe other numeric DataTypes have this issue too with postgres.
Thanks for addressing this!

**Comment by mariusa** [comment]
Also, ARRAY defaultValue is now ```"ARRAY[]"```, should be ```[]```

**Comment by steveschmitt** [comment]
Fixed in 0.6.1

**Comment by mariusa** [comment]
Thanks @steveschmitt !

I've tested with 0.6.1 and there's an issue with ARRAY.

Generated code is `defaultValue: ARRAY[]`
It should be `defaultValue: []`

Also `type: DataTypes.ARRAY,` should be `DataTypes.ARRAY(Sequelize.TEXT),`
(whatever the field type is)

**Comment by steveschmitt** [comment]
I know, but the sequelize `describeTable` won't tell me the underlying type in the array!  
Please file a separate issue for this (but there may be one already).

**Comment by mariusa** [comment]
Right, there's #151

I'm looking to make a PR to fix 
generated code is `defaultValue: ARRAY[]`
should be `defaultValue: []`

**Comment by mariusa** [comment]
Actually, the `defaultValue` isn't an issue. Solved by using the modern syntax
https://stackoverflow.com/a/53494659/212736

**Comment by steveschmitt** [comment]
I used the `'{}'` syntax in my testing, that's why I didn't see the problem.

**Comment by mariusa** [comment]
It's no problem :) I updated my old syntax.

**Comment by mariusa** [comment]
Hi @steveschmitt 
Found a new issue with setting the default array value. When the db has a default value, eg

```
CREATE TABLE test
( 
    permissions TEXT[] DEFAULT '{"Admin", "Reports"}'
);
```
the model won't be extracted properly:

```
 permissions: {
      type: DataTypes.ARRAY(DataTypes.TEXT),
      allowNull: true,
      defaultValue: [Admin,Reports]
    },
```

values should be as strings, eg
```
defaultValue: ["Admin","Reports"]
```

FYI https://github.com/rails/rails/issues/9127

Thanks!
