### ISSUE TITLE
using --lang es6 generates #TABLE# class name

### ISSUE THREAD

**Issue by fprijate** [sequelize/sequelize-auto#432]
using:
sequelize-auto -h localhost  --database xxx.db --dialect sqlite --lang es6  --cm p --config config.json --additional add.json

generates:

/* jshint indent: 1 */

const Sequelize = require('sequelize');
module.exports = (sequelize, DataTypes) => {
	return Blago.init(sequelize, DataTypes);
}

class **#TABLE#** extends Sequelize.Model {
	static init(sequelize, DataTypes) {

**Comment by steveschmitt** [comment]
Thanks for catching this!  Clearly I didn't test this change properly.
And thanks for PR #433 that fixes it.
