### ISSUE TITLE
mismatch between additional arguments

### ISSUE THREAD

**Issue by fprijate** [sequelize/sequelize-auto#434]
additional (-a) argument can be obtained from command line and must be name ob JSON file.
.alias('a', 'additional').config('a')   

Later (line 77) 
if (configFile.additional) {
  additional = configFile.additional;
}

program expects it to be an object  in config file like 
{ 
   ...
   "additional" : {
       "paranoid": true
   }
}

which is mismatch.
There is solution
1.  change 
     .alias('a', 'additional').config('a') 
       to    
      .alias('a', 'additional').string('a')

**Comment by steveschmitt** [comment]
Thanks for catching this, and thanks for PR #433 that fixes it.
