### ISSUE TITLE
Comment with newline breaks the code

### ISSUE THREAD

**Issue by alkaaf** [sequelize/sequelize-auto#439]
I have few new line on my table column comment and the generated code looks like this
![image](https://user-images.githubusercontent.com/13295107/96583801-785d2080-1307-11eb-815e-ca41bc5a9c7b.png)
Hope this will be fixed soon.

do something like excluding comment generation option that i am missing?

**Comment by steveschmitt** [comment]
Thanks for finding this.  It will be fixed in the next release.

**Comment by steveschmitt** [comment]
Fixed in 0.6.5.
