### ISSUE TITLE
Bug: Foreign key detection not working for sqlite

### ISSUE THREAD

**Issue by simov** [sequelize/sequelize-auto#44]
:wave: I'm trying to generate the same models for different dialects:

![screenshot from 2016-01-02 19 32 52](https://cloud.githubusercontent.com/assets/1694112/12075426/1f9a1ece-b189-11e5-9751-ef5e5d419bf1.png)

And it turns out that sequelize-auto doesn't expect the correct data structure returned after executing `PRAGMA foreign_key_list(table);`:

![screenshot from 2016-01-02 19 37 08](https://cloud.githubusercontent.com/assets/1694112/12075425/1d29eca0-b189-11e5-9cb9-1843d4107341.png)

Hence the above code fails always, I guess that's why I'm not getting the `references` key in the model?

Let me know if I need to supply more information.

**Comment by durango** [comment]
Let me know if you run into any issues, sorry about that.
