### ISSUE TITLE
How to use initModels(sequelize);

### ISSUE THREAD

**Issue by nicolas15000** [sequelize/sequelize-auto#441]
Hi, 
This is my code
```
     var x = require('./models/init-models.js');
    x.initModels(sequelize);

    var DataTypes = require('sequelize/lib/data-types');
    var customers = require('./models/customers.js')(sequelize, DataTypes);

    customers.findAll().then((c) => {
        console.log(c);
        console.log('********************')

    }).finally(() => {
        sequelize.close();
    });

```
findAll() is working , 
How can I use initModels to set up the customers instead of setting a customers like I did ?

This is my init-models.js generated file : 

```
var DataTypes = require("sequelize").DataTypes;
var _customers = require("./customers");
var _orders = require("./orders");
var _employees = require("./employees");
var _orderdetails = require("./orderdetails");
var _offices = require("./offices");
var _payments = require("./payments");
var _products = require("./products");
var _productlines = require("./productlines");

function initModels(sequelize) {
    console.log('passe')
    var customers = _customers(sequelize, DataTypes);
    var orders = _orders(sequelize, DataTypes);
    var employees = _employees(sequelize, DataTypes);
    var orderdetails = _orderdetails(sequelize, DataTypes);
    var offices = _offices(sequelize, DataTypes);
    var payments = _payments(sequelize, DataTypes);
    var products = _products(sequelize, DataTypes);
    var productlines = _productlines(sequelize, DataTypes);

    return {
        customers,
        orders,
        employees,
        orderdetails,
        offices,
        payments,
        products,
        productlines,
    };
}
module.exports = { initModels };

```

**Comment by steveschmitt** [comment]
You could do it like this: 
```js
var initModels = require("./models/init-models").initModels; 

var models = initModels(sequelize);

var customers = models.customers;
var orders = models.orders;
```
See `sample-es5.js` in the [sample](https://github.com/sequelize/sequelize-auto/tree/master/sample) folder.

**Comment by nicolas15000** [comment]
Thanks a lot !

**Comment by saadmomin** [comment]
I am on v6 and am stuck on this. I have below setup:

init-models.js : 
products.belongsTo(productlines, { as: "productLine_productline", foreignKey: "productLine"});
productlines.hasMany(products, { as: "products", foreignKey: "productLine"});

Trying this :
include: [{
    model: productlines,
    as: 'productLine_productline'
  }],

Getting below error:
UnhandledPromiseRejectionWarning: SequelizeEagerLoadingError: productlines is not associated to products!

Please assist!!

**Comment by steveschmitt** [comment]
Did you get any errors from running the `initModels` method?

I think there might have a problem with capitalization.

**Comment by saadmomin** [comment]
I am sorry I am new to this. I am not sure where to initialize it. init-models.js file is created and I dont get any errors when running the app.

**Comment by Delord-Nzanzu** [comment]
hello please help me a have error sequelize.define is not a function
const sequelize = require("sequelize");
const initModels=require("../models/init-models").initModels;
const models=initModels(sequelize)
where is a problem?? please helps!!!

**Comment by steveschmitt** [comment]
@Delord-Nzanzu You need to construct an instance of Sequelize, and pass that to `initModels`.  Something like:
```js
const Sequelize = require("sequelize");
const initModels = require("./models/init-models");
const config = require("./config/config");

// create sequelize instance
const sequelize = new Sequelize(
  config.dbname,
  config.user,
  config.pass,
  config.options
);
const models = initModels(sequelize);

```

**Comment by Delord-Nzanzu** [comment]
Presse what is the importance of the redefinition of sequelize which carries its instances or we are already going to initialize in app.json???

**Comment by Delord-Nzanzu** [comment]
@steveschmitt please what is the importance of the redefinition of sequelize which carries its instances or we are already going to initialize in app.json

**Comment by steveschmitt** [comment]
Please read the [Sequelize documentation](https://sequelize.org/master/manual/getting-started.html).

**Comment by junkiet** [comment]
this can make more simple, auto load at all, and models insert into event, and you can direct use event.models from defineEventHandler() for nuxtjs
```
// server/plugins/loadModels.js
import fs from 'fs/promises';
import path from 'path';
import { pathToFileURL } from 'url';
export default defineNitroPlugin((nitroApp) => {
    nitroApp.hooks.hook('request', async (event) => {
        const dir = 'data';
        const __dirname = path.resolve();
        const modelsDirectory = path.join(__dirname, 'models', dir);
    
        let models = {};
        const files = await fs.readdir(modelsDirectory);
        await Promise.all(
            files.map(async (file) => {
                if (!file.includes('database') && !file.includes('init')) {
                    const modelPath = path.join(modelsDirectory, file);
                    const {href: importModelPath} = pathToFileURL(modelPath);
                    const { sequelize } = await import(importModelPath);
                    models = sequelize.models;
                }
            })
        );
        event.models = models;
    });
})
```
