### ISSUE TITLE
Obtaining comments ruins the whole query with 'More than one row returned by a subquery used as an expression' error

### ISSUE THREAD

**Issue by pphunor** [sequelize/sequelize-auto#442]
I have tried to generate models from a postgres database, where there are several schemas with exactly the same structure. Due to missing schema filtering in a subquery (to get column descriptions) the whole process fails. To resolve this the where clause should be completed with an extra condition: **c.table_schema = st.schemaname**
```
(SELECT pgd.description FROM pg_catalog.pg_statio_all_tables AS st INNER JOIN pg_catalog.pg_description pgd on (pgd.objoid=st.relid) 
	 	WHERE c.ordinal_position=pgd.objsubid AND c.table_name=st.relname) AS "Comment"
```

**Comment by steveschmitt** [comment]
I think you are right about the fix.  But **sequelize-auto** uses `queryInterface.describeTable(table_name, table_schema)` from **sequelize** to get the table information.

So you need to report this issue in the [sequelize/sequelize](https://github.com/sequelize/sequelize) repo.
