### ISSUE TITLE
ERR_INVALID_ARG_TYPE when using programmatic API

### ISSUE THREAD

**Issue by zero245** [sequelize/sequelize-auto#447]
(node:47657) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)

this is pretty much the code:

  1 var SequelizeAuto = require('sequelize-auto')
  2 
  3 
  4 //With options:
  5 //var auto = new SequelizeAuto('database', 'user', 'pass', {
  6 var auto = new SequelizeAuto('*****', {', '*****', {', '*****', {
  7     host: 'localhost',
  8     dialect: 'postgres',
  9     directory: false, // prevents the program from writing to disk
 10     port: '5432',
 11 //    camelCase: true, // convert snake_case column names to camelCase field names: user_id -> userId
 12  //   camelCaseFileName: true, // file names created for each model use camelCase.js not snake_case.js
 13     additional: {
 14         timestamps: true
 15         //...
 16     },
 17     //tables: ['table1', 'table2', 'myschema.table3'] // use all tables if omitted
 18     //...
 19 })
 20 
 21 auto.run()
 22 .then(data => {
 23   console.log(data.tables);      // table list
 24   console.log(data.foreignKeys); // foreign key list
 25   console.log(data.text)         // text of generated files
 26 });
 27

**Comment by zero245** [comment]
Is path a new option now?  I have being used this since 0.3 and the last version I used was 0.5, did something change?

**Comment by steveschmitt** [comment]
The `directory` option (line 9 of your code) should contain the output path for the models.  Omit it to use the default path, "./models".  If you don't want the output written, then use the `noWrite` option.

Setting "directory: false" to mean "noWrite" seems reasonable, but that's not the way it works right now.

**Comment by zero245** [comment]
I see seems the project is still working out the API conventions ATM.  Just wonder if this will be changing till it reaches 1.0?

**Comment by zero245** [comment]
in which case, should we just out put the .js file to stdout in case there is no path or directory provided. Just a thought.

**Comment by zero245** [comment]
On second thought, that might be a security issue to dump the model into stdout. RFC

**Comment by steveschmitt** [comment]
Yes, we will probably be changing the API as we add features.

I don't think we will change the `directory` or `noWrite` options, but I am open to suggestions.

**Comment by steveschmitt** [comment]
Fixed in 0.7.4.   Now when directory = false, it won't attempt to write output.  

Thanks for finding this.
