### ISSUE TITLE
Auto increment is missing

### ISSUE THREAD

**Issue by devonik** [sequelize/sequelize-auto#448]
As in #248 described the issue should be fixed.

But probably it seems to be there. I'm using postgress and sequlize@0.7.2 and the result is always:

![grafik](https://user-images.githubusercontent.com/16446467/100075073-c94cc100-2e3f-11eb-8ff5-1e6ee06c37b1.png)

I'm sure that I declared it as autoIncrement in the database. Can you reproduce it?

**Comment by steveschmitt** [comment]
Fixed in 0.7.3
