### ISSUE TITLE
Auto increment missing in postgreSQL?

### ISSUE THREAD

**Issue by rtkhanas** [sequelize/sequelize-auto#45]
I have a table:

```sql
CREATE TABLE "user"
(
  user_id serial NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
)
```

And a result is:

```javascript
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('user', {
    user_id: {
      type: DataTypes.INTEGER,
      primaryKey: true
    }
  }, {
    tableName: 'user',
    freezeTableName: true,
    timestamps: false,
  });
};
```

However I expected to see "autoIncrement: true" for the "user_id" column. 

I'm new to postgreSQL db, but I believe auto increment should be there.

**Comment by durango** [comment]
Just tried on the latest...

```js
/* jshint indent: 2 */

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('user', {
    user_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    }
  }, {
    tableName: 'user',
    freezeTableName: true
  });
};
```

Which version of postgres are you running?

**Comment by rtkhanas** [comment]
That is what I've got:
"PostgreSQL 9.4.5 on x86_64-apple-darwin, compiled by i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1"

I also use config.json for sequelize and it looks like this:

````json
{
  "port": 5432,
  "dialect": "postgres",
  "additional" : {
    "freezeTableName" : true,
    "timestamps": false
  }
}
````

Sequelize version: 3.15.1

**Comment by igor-galchevsky** [comment]
@rtkhanas, are you using sequelize or sequelize-auto? I can confirm that sequelize-auto v0.2.7 does generate the same correct response for me as @durango posted.

If you use sequelize-auto then
1. which version?
2. could you post complete command line here?

**Comment by rtkhanas** [comment]
@igor-galchevsky, I would say sequelize and sequelize-auto just for generating models, my fault. That is why I'm asking this question here :)

1. The same - v0.2.7
2. sequelize-auto -h localhost -d myProject -u postgres -x qwerty -c ./db/config.json -o ./src/data-access/model

**Comment by durango** [comment]
Closing this issue, feel free to re-open but it seems like postgres is working great now.
