### ISSUE TITLE
Postgres ENUM broken.

### ISSUE THREAD

**Issue by defiantgoat** [sequelize/sequelize-auto#455]
I've just started testing this library with a db that uses ENUMS for some column types. The model type is always written to the file with the `udt_name`

For example:
`    food_type: {
      type: "food_type_enum",
      allowNull: true
    }`

I can see from adding comments to the built code in the node module that the ENUM values are available in the `special` array. However, auto-builder changes the type to `udt_name` from `"USER-DEFINED"` but then auto-genereator which is called after looks for `fieldObj.type === "USER-DEFINED"` in order to write the ENUM values.

How can it ever find a type of `USER-DEFINED` if it has been changed? Am I missing some config I need to add to the run script?

https://github.com/sequelize/sequelize-auto/blob/master/src/auto-builder.ts#L139

https://github.com/sequelize/sequelize-auto/blob/master/src/auto-generator.ts#L213

**Comment by steveschmitt** [comment]
Ugh, sorry, I probably broke this recently.  I'll try to fix it soon.

**Comment by defiantgoat** [comment]
@steveschmitt All good. The library is great otherwise.

**Comment by steveschmitt** [comment]
Fixed in 0.7.5.  Thanks for your help.
