### ISSUE TITLE
PostgreSQL 11 autoIncrement missing

### ISSUE THREAD

**Issue by divinebovine** [sequelize/sequelize-auto#459]
Using sequelize-auto 0.7.4 with Postgresql 11, autoIncrement is missing from our tables
Example:
![image](https://user-images.githubusercontent.com/2818169/101222659-d93e7f00-364f-11eb-9101-87665bcc8d38.png)
![image](https://user-images.githubusercontent.com/2818169/101222717-fe32f200-364f-11eb-8031-1f9031a762ee.png)

**Comment by katyduong** [comment]
I have the same issue as well. I have updated `sequelize-auto` to the latest version but still not sure what's still holding it back from adding the `autoIncrement` field

**Comment by divinebovine** [comment]
@katyduong the code hasn't been released yet.

**Comment by steveschmitt** [comment]
@divinebovine The update should be in 0.7.5, which is released now.  Are you still having the problem?

I confess that I did not test your scenario specifically.

**Comment by divinebovine** [comment]
@steveschmitt It looks good now that I updated. I think @katyduong ran into the problem before you released the new update. 🤷

**Comment by katyduong** [comment]
Hi yall. I tested the new version and it seemed to finally add back `autoIncrement`. Marvelous work! Thank you all for your quick responses 😄

**Comment by steveschmitt** [comment]
Thanks for you patience.
