### ISSUE TITLE
No files created as output

### ISSUE THREAD

**Issue by tejuguasu** [sequelize/sequelize-auto#461]
I've installed the package with `npm install --save-dev sequelize-auto` after installing sequelize, pg, and pg-hstore.

Executing `npx sequelize-auto -o "./src/models" -h <server_by_url> -d <database_name> -u <user_name> -x <password> --dialect postgres` gives me the following output but no files are created:

```
{
  spaces: true,
  indentation: 2,
  directory: './src/models',
  additional: {},
  dialect: 'postgres',
  port: 5432,
  host: 'server_by_url',
  storage: 'database_name',
  tables: null,
  skipTables: null,
  schema: undefined,
  lang: 'es5',
  caseModel: 'o',
  caseFile: 'o',
  caseProp: 'o',
  noWrite: false,
  views: false,
  singularize: false
}
```

Am I missing something?
I know creating an issue is not the best way to ask, but there are not docs about this, and StackOverflow questions regarding sequelize-auto are not receiving answers.

**Comment by steveschmitt** [comment]
Sorry, I should start paying attention to StackOverflow.

In your command line, what is 'server_by_url'?  It should just be the hostname or IP address, not a URL.

**Comment by tejuguasu** [comment]
If you can, it would greatly encourage the use of the package. Even then, I appreciate whichever effort you put in answering.

The `server_by_url` is the hostname, like `myproject.example.com`, is it supported?

**Comment by steveschmitt** [comment]
If it can't connect to the server, it should give you an error at the very least.

Does your `./src/models` directory exist?

Can you try using the [programmatic API](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api) and create the Sequelize instance first?   (See 3rd example in the [programmatic API](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api) section)

**Comment by tejuguasu** [comment]
I will try your suggestions, The directory already exists.

**Comment by tejuguasu** [comment]
You are right, creating programmatically worked, so I will just create a script for that.

Curious why running the command with args is outputting sort-off configuration information, though. If I got time to look into it I will complete that bit of information here.

Thank you again!

**Comment by steveschmitt** [comment]
Outputting the configuration information is supposed to help us debug these sorts of problems with the command line -- but it didn't help much here!

Sorry about the problem, glad you were able to fix it.
