### ISSUE TITLE
text array default values not escaped to strings when extracted

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize-auto#474]
Hi Steve,
Found a new issue with setting the default array value. When the db has a default value, eg

```
CREATE TABLE test
( 
    permissions TEXT[] DEFAULT '{"Admin", "Reports"}'
);
```
the model won't be extracted properly:

```
 permissions: {
      type: DataTypes.ARRAY(DataTypes.TEXT),
      allowNull: true,
      defaultValue: [Admin,Reports]
    },
```

values should be as strings, eg
```
defaultValue: ["Admin","Reports"]
```

FYI https://github.com/rails/rails/issues/9127

Thanks!

**Comment by steveschmitt** [comment]
Fixed in 0.7.7
