### ISSUE TITLE
Regression: Typescript enums are now labeled as `any` instead of the actual options

### ISSUE THREAD

**Issue by JonathanWolfe** [sequelize/sequelize-auto#479]
Looks like something in commit [f63a037da4162abd1f13ad9f4e48b8444b02d56a1](https://github.com/sequelize/sequelize-auto/commit/f63a037da4162abd1f13ad9f4e48b8444b02d56a) caused a regression that make enums be printed as `any` in the typescript output format.

I'd wager that it's this line: [`src/auto-generator.ts:626`](https://github.com/sequelize/sequelize-auto/commit/f63a037da4162abd1f13ad9f4e48b8444b02d56a#diff-421f07eb1cd9b128a305ab260e56553b8c35baa97bf85e27e01b77b96d8d5e66R626)

I'll open a PR with fixes later this week if you don't happen to get to it by then

**Comment by steveschmitt** [comment]
Good catch, and thanks for your help.  I'm pretty busy at the moment, and haven't had time to work on sequelize-auto for a while.

**Comment by steveschmitt** [comment]
It's working for me in my testing.  I wonder what is different about yours?

In my postgres db, I have the type definition
```
CREATE TYPE public.color_t AS ENUM ('green', 'red', 'blue', 'Yellow');
```
Then in a table definition I have a column
```
    "Color1" color_t,
```
And my TypeScript output looks like
```js
  Color1?: "green" | "red" | "blue" | "Yellow";
```

**Comment by JonathanWolfe** [comment]
Oh, I should have put in the original ticket that it does work for postgres, but not other dbs. I'm specifically on MySQL with a column like `alter table fooBar add column test enum('one','Two','THREE') not null default 'one';`
