### ISSUE TITLE
mark 'id' column as PK, if no other PK is present

### ISSUE THREAD

**Issue by mariusa** [sequelize/sequelize-auto#480]
Hi,

Using a table and a view on that table:

```
CREATE TABLE dev
(
    id TEXT NOT NULL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
);

CREATE OR REPLACE VIEW dev_v AS
SELECT id, email FROM dev; -- actually there's more data here

```

Extracting models with sequelize-auto generates this for the view

```
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('dev_v', {
        id: {
            type: DataTypes.TEXT,
            allowNull: true
        },
        email: {
            type: DataTypes.TEXT,
            allowNull: true
        },
...
```

but then sequelize gives
`ERROR uncaughtException A column called 'id' was added to the attributes of 'dev_v' but not marked with 'primaryKey: true'
`

To avoid this, the generated model should be

```
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('dev_v', {
        id: {
            type: DataTypes.TEXT,
            allowNull: true,
            primaryKey: true
        },
        email: {
            type: DataTypes.TEXT,
            allowNull: true
        },

```

For models which have an 'id' column and no PK is present, would you please include `primaryKey: true` in the generated model?

From sequelize changelog:
`An error is thrown if a column called id is added, but not marked as primary key, and no other pk is present. #4139`

Thanks!

**Comment by steveschmitt** [comment]
Fixed in 0.7.10
