### ISSUE TITLE
 'export *' does not re-export a default.

### ISSUE THREAD

**Issue by chaoren1641** [sequelize/sequelize-auto#481]
The first line of code I generated looks something like this, which obviously returns an error:

import Sequelize, { DataTypes, Model, Optional } from 'sequelize';
![image](https://user-images.githubusercontent.com/404245/104584254-43a9fc80-569d-11eb-99b5-8577f682a378.png)

**Comment by steveschmitt** [comment]
What version of TypeScript are you using?  It works for me with TypeScript 4.1.2

**Comment by chaoren1641** [comment]
sorry，This is due to a problem with my TypeScript version, which is 3.9 locally

**Comment by papb** [comment]
The correct way to import should be `import { Sequelize, DataTypes } from 'sequelize'`

**Comment by steveschmitt** [comment]
We are using
```js
import Sequelize, { DataTypes, Model, Optional } from 'sequelize';
```
to import the Sequelize _namespace_, not the type.  So later we can do:
```js
getOrderItems!: Sequelize.HasManyGetAssociationsMixin<OrderItem>;
```
otherwise, we would have to import all the mixin functions individually:
```js
import { Sequelize, DataTypes, Model, Optional, HasManyGetAssociationsMixin, HasManyAddAssociationMixin, 
  HasManyAddAssociationsMixin, HasManyCountAssociationsMixin, HasManyCreateAssociationMixin, HasManyHasAssociationMixin, 
  HasManyHasAssociationsMixin, HasManyRemoveAssociationMixin, HasManyRemoveAssociationsMixin, HasManySetAssociationsMixin } from 'sequelize';
```

**Comment by papb** [comment]
Ah, ok!

**Comment by chaoren1641** [comment]
Generated names are not very formal, such as interfaces and types that start with I and class names that start with a capital case. Can this be improved?

**Comment by steveschmitt** [comment]
Use `--caseModel p` option to make class names in PascalCase.  The default is to use the same as the table name in the database.

I think starting interface names with "I" is an antipattern.
