### ISSUE TITLE
Can't use config file for database or host name.

### ISSUE THREAD

**Issue by twastvedt** [sequelize/sequelize-auto#482]
The Sequelize documentation linked to for the config json file has several fields that aren't currently being used. Most notably, specifying a database or host in the config file does not prevent the command line from requiring those arguments. Here's a commit that changes this, that's working for me: https://github.com/twastvedt/sequelize-auto/commit/0412cfb44264dd44a29a17ba3d2551b962bb674c. I'm happy to make a PR, but I wanted to check things out first as I'm not overly familiar with this project. (If this is the right direction I'll add back in the `demand` after checking the config object.) Thanks!

**Comment by steveschmitt** [comment]
Yes, your changes look good.  Please open the PR.
Thanks!

**Comment by steveschmitt** [comment]
Fixed in 0.8.0.  Thanks for your commit.

**Comment by twastvedt** [comment]
@steveschmitt Thanks! Sorry I didn't get to making that PR.
