### ISSUE TITLE
Error reading CASE Sensitive SQL Database

### ISSUE THREAD

**Issue by AndreasSchindler** [sequelize/sequelize-auto#486]
SQLServer allows to have case sensitive databases. In this case the name of System Tables has to be in Capital Letters (INFORMATION_SCHEMA) 

Patch to fix the issue:
diff --git a/node_modules/sequelize-auto/lib/dialects/dialect-options.js b/node_modules/sequelize-auto/lib/dialects/dialect-options.js
index da51fca..d579d0e 100644
--- a/node_modules/sequelize-auto/lib/dialects/dialect-options.js
+++ b/node_modules/sequelize-auto/lib/dialects/dialect-options.js
@@ -12,21 +12,21 @@ function makeCondition(columnName, value) {
 exports.makeCondition = makeCondition;
 function showTablesGeneric(schemaName) {
     return `SELECT table_name, table_schema
-            FROM information_schema.tables
+            FROM INFORMATION_SCHEMA.TABLES
            WHERE table_type = 'BASE TABLE'
                  ${makeCondition("table_schema", schemaName)}`;
 }
 exports.showTablesGeneric = showTablesGeneric;
 function showViewsGeneric(schemaName) {
     return `SELECT table_name, table_schema
-            FROM information_schema.tables
+            FROM INFORMATION_SCHEMA.TABLES
            WHERE table_type = 'VIEW'
                  ${makeCondition("table_schema", schemaName)}`;
 }
 exports.showViewsGeneric = showViewsGeneric;
 function countTriggerGeneric(tableName, schemaName) {
     return `SELECT COUNT(0) AS trigger_count
-            FROM information_schema.triggers AS t
+            FROM INFORMATION_SCHEMA.TRIGGERS AS t
            WHERE t.event_object_table = ${addTicks(tableName)}
                  ${makeCondition("t.event_object_schema", schemaName)}`;
 }

**Comment by steveschmitt** [comment]
Fixed with your changes in 0.7.8
