### ISSUE TITLE
Include error due to Association

### ISSUE THREAD

**Issue by saadmomin** [sequelize/sequelize-auto#488]
I am on v6 and am stuck on this. I have below setup:

init-models.js :
products.belongsTo(productlines, { as: "productLine_productline", foreignKey: "productLine"});
productlines.hasMany(products, { as: "products", foreignKey: "productLine"});

Trying this :
include: [{
model: productlines,
as: 'productLine_productline'
}],

Getting below error:
UnhandledPromiseRejectionWarning: SequelizeEagerLoadingError: productlines is not associated to products!

Help will be appreciated. Please assist!!

**Comment by steveschmitt** [comment]
Can you provide more of your code, the init-models and the model definitions

**Comment by papb** [comment]
Hi @steveschmitt, sorry for the off-topic comment, can you please contact me on [Slack](https://sequelize.slack.com/) later? You can mention me there with `@Pedro A P B`. And thanks once again for the great work you've been doing here!! (I'll delete this comment afterwards to not clutter this issue)

**Comment by steveschmitt** [comment]
@papb I'm not on the sequelize.slack.com workspace.

**Comment by papb** [comment]
@steveschmitt Ah! Can you please try [this link](http://sequelize-slack.herokuapp.com/) to solve that?

**Comment by steveschmitt** [comment]
@saadmomin I think I fixed it in 0.7.9

**Comment by steveschmitt** [comment]
Fixed in 0.7.10
