### ISSUE TITLE
bug: You have used the alias ${options.as} in two separate associations

### ISSUE THREAD

**Issue by zucatti** [sequelize/sequelize-auto#489]
in Sakila demo database, import via latest version of sequelize-auto, got the exception "You have used the alias ${options.as} in two separate associations"

remove this  (auto generated by sequelize-auto)
staff.hasOne(store, {
        as: "store",
        foreignKey: "manager_staff_id"
    }); seems to resolve the bug
keep up the good work ! Sequelize-auto is awesome.

**Comment by steveschmitt** [comment]
Thanks for reporting this.  

What version of `sequelize-auto` did you find this in?  0.7.8 or 0.7.9?

**Comment by steveschmitt** [comment]
I've installed sakila-db, and I have reproduced the problem.  My de-duplication algorithm is naïve.

**Comment by steveschmitt** [comment]
Fixed in 0.7.10
