### ISSUE TITLE
Postgres daterange type should not be DataType.Date

### ISSUE THREAD

**Issue by defiantgoat** [sequelize/sequelize-auto#490]
A column that is a daterange type in Postgres should be a type similar to:

`type: DataTypes.RANGE(DataTypes.DATEONLY)`

currently it produces:
` type: DataTypes.DATE`

**Comment by steveschmitt** [comment]
More Postgres types!  :)  Thanks.

**Comment by steveschmitt** [comment]
Fixed in 0.7.10
