### ISSUE TITLE
Having problems with include, I am sure I am not doing it right

### ISSUE THREAD

**Issue by AlanGreyjoy** [sequelize/sequelize-auto#492]
Everything is default generated. 

I am on the newest version.

`userposts.belongsTo(users, { as: "user", foreignKey: "userId"});`
`users.hasMany(userposts, { as: "userposts", foreignKey: "userId"});`

`let myPosts = await models.userposts.findAll({where:{userId: user.id}, include: models.users})`

Error
UnhandledPromiseRejectionWarning: Error: Include unexpected. Element has to be either a Model, an Association or an object.

**Comment by steveschmitt** [comment]
Since **userposts** belongsTo **users** as "user", then **userposts** should have a property called `user`.  So try
```js
let myPosts = await models.userposts.findAll({where:{userId: user.id}, include: "user"});
```

**Comment by steveschmitt** [comment]
Closing because I think it is working.
