### ISSUE TITLE
MSSQL Identity (autoIncrement) field contains wrong datatype

### ISSUE THREAD

**Issue by Johnne25** [sequelize/sequelize-auto#496]
I autogenerated my models and it assigned the autoIncrement files as Datatype.DOUBLE.
When I launch my application it performs a sequalize database check and throws an error:

`original: RequestError: Identity column 'RoleCapabilityID' must be of data type int, bigint, smallint, tinyint, or decimal or numeric with a scale of 0, unencrypted, and constrained to be nonnullable.`

Looks like identify fields should be cast as DataType.NUMERIC.

I am generating from Microsoft SQL Server 2019.

**Comment by Johnne25** [comment]
RoleCapabilityID: {
      autoIncrement: true,
      type: DataTypes.DOUBLE,
      allowNull: false,
      primaryKey: true
    },

Should be: 
    RoleCapabilityID: {
      autoIncrement: true,
      type: DataTypes.NUMERIC,
      allowNull: false,
      primaryKey: true
    },

**Comment by steveschmitt** [comment]
Thanks for reporting this.  What is the definition of the field in the database?

**Comment by steveschmitt** [comment]
You are right - it's a bug.  Actually, this was a problem affecting all MSSQL NUMERIC columns.  Fixed in the above commit; will be in the next release.

**Comment by steveschmitt** [comment]
Fixed in 0.7.11
