### ISSUE TITLE
New aliases breaking queries

### ISSUE THREAD

**Issue by divinebovine** [sequelize/sequelize-auto#497]
### Description
Sometime between versions 0.7.5 and 0.7.10, sequelize-auto has started generating aliases for every relationship.
Example:
![image](https://user-images.githubusercontent.com/2818169/107265133-87c4be80-6a09-11eb-8645-5cfb01fa664c.png)

### Issue
This breaks existing codebases that join tables unless they specifically declare the alias with the **exact same string.**

### Error text
"agencies is associated to companies using an alias. You must use the 'as' keyword to specify the alias within your include statement.

### Examples
No alias throws exception:
```js
await this.myDb.companies.findOne({
      include: [
        { model: this.myDb.agencies}
      ],
```

Wrong alias string throws exception:
```js
await this.myDb.companies.findOne({
      include: [
        { model: this.myDb.agencies, as: 'user_agencies' }
      ],
```

Correct alias does NOT throw:
```js
await this.myDb.companies.findOne({
      include: [
        { model: this.myDb.agencies, as: 'agencies' },
      ],
```

**Comment by divinebovine** [comment]
I believe this code change introduced the regression.

https://github.com/sequelize/sequelize-auto/commit/d3093bbf050a3d1e47061890891565845c30bb2f#diff-691d3f6eaae547b6a90f6852de227f7a4399f0dc6487c3796838c27955b1fe06R92-R101

**Comment by steveschmitt** [comment]
You are right.  The alias was needed to fix the problem of multiple relationships between the same two entities.  For example, suppose `companies` also had a `primary_agency_id`; or suppose `agencies` had a `previous_company_id`.

Perhaps we can introduce a flag to turn off aliases for users who don't need it.

BTW, with aliases, you don't need to specify the model at all in your include:
```js
await this.myDb.companies.findOne({
      include: ['agencies'],
...
```
Sequelize can determine the model from the alias; it's a shame it can't do the reverse, or we wouldn't be having this conversation.

**Comment by divinebovine** [comment]
Thanks for your suggestion! I've said it before but I'm not an expert with sequelize. I've just inherited a project utilizing it.

**Comment by steveschmitt** [comment]
Closing this as I think it is working.
