### ISSUE TITLE
ts model issues

### ISSUE THREAD

**Issue by dengzikun** [sequelize/sequelize-auto#499]
The properties of `dataValues `that returned from `findAll `are all `undefined`. The `_previousDataValues `is correct.

sequelize: 6.3.5
sqlite3: 5.0.0
sequelize-auto: 0.7.11
typescript: 4.1.5

**Comment by steveschmitt** [comment]
Can you provide your table definition, model code that was produced by sequelize-auto, and your code that performs the `findAll`?

**Comment by dengzikun** [comment]
table definition:

`-- Drop table

-- DROP TABLE JGSY_COMMON;

CREATE TABLE JGSY_COMMON (
	JGSY_CODE VARCHAR(100) NOT NULL,
	JGSY_PARENT_CODE VARCHAR(100),
	DEP_CODE VARCHAR(6),
	JGSY_NAME VARCHAR(200),
	JGSY_TYPE VARCHAR(2),
	JGSY_PARENT_TYPE VARCHAR(2),
	JGSY_SYSTEM_CODE VARCHAR(2),
	JGSY_STATES VARCHAR(2),
	JGSY_CHILDRENSUM DOUBLE,
	JGSY_CODE_ORDER VARCHAR(100),
	UPDATE_TIME TIMESTAMP,
	CHEXIAO_TIME TIMESTAMP,
	CHEXIAO_WH VARCHAR(100),
	CHEXIAO_SYSTEM_TIME TIMESTAMP,
	EDITION DOUBLE,
	UPDATE_UNIT VARCHAR(100),
	JGSY_STANDBY1 VARCHAR(100),
	JGSY_STANDBY2 VARCHAR(100),
	JGSY_IFVERTICAL VARCHAR(1),
	JGSY_RYSBFS VARCHAR(2),
	JGSY_SZBM VARCHAR(100),
	JGSY_CHECKSTATE DOUBLE,
	JGSY_IFCZGLBM VARCHAR(1),
	JGSY_IFZFJG VARCHAR(1),
	CHEXIAO_YY VARCHAR(32),
	IF_SHENPI VARCHAR(1),
	JGBZ_ID VARCHAR(32),
	JGSY_CHAOJG VARCHAR(1),
	JGSY_CHAOBZ VARCHAR(1),
	JGSY_CHAOZS VARCHAR(1),
	JGSY_STANDBY3 VARCHAR(100),
	JGSY_STANDBY4 VARCHAR(100),
	JGSY_STANDBY5 VARCHAR(100),
	JGSY_STANDBY6 VARCHAR(100),
	JGSY_STANDBY7 VARCHAR(100),
	CREDIT_CODE VARCHAR(100),
	`sfskfq` VARCHAR(1),
	`is_create` VARCHAR(10),
	`jgsy_code_old` VARCHAR(100),
	JGSY_IFZSSYDW VARCHAR(255),
	`jgsy_bzsycj` VARCHAR(2),
	CONSTRAINT SYS_PK_12328 PRIMARY KEY (JGSY_CODE)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_12328_12329 ON JGSY_COMMON (JGSY_CODE);`

model produced by sequelize-auto:

`import Sequelize, { DataTypes, Model, Optional } from 'sequelize';

export interface JgsyCommonAttributes {
  jgsyCode: string;
  jgsyParentCode?: string;
  depCode?: string;
  jgsyName?: string;
  jgsyType?: string;
  jgsyParentType?: string;
  jgsySystemCode?: string;
  jgsyStates?: string;
  jgsyChildrensum?: number;
  jgsyCodeOrder?: string;
  updateTime?: Date;
  chexiaoTime?: string;
  chexiaoWh?: string;
  chexiaoSystemTime?: string;
  edition?: number;
  updateUnit?: string;
  jgsyStandby1?: string;
  jgsyStandby2?: string;
  jgsyIfvertical?: string;
  jgsyRysbfs?: string;
  jgsySzbm?: string;
  jgsyCheckstate?: number;
  jgsyIfczglbm?: string;
  jgsyIfzfjg?: string;
  chexiaoYy?: string;
  ifShenpi?: string;
  jgbzId?: string;
  jgsyChaojg?: string;
  jgsyChaobz?: string;
  jgsyChaozs?: string;
  jgsyStandby3?: string;
  jgsyStandby4?: string;
  jgsyStandby5?: string;
  jgsyStandby6?: string;
  jgsyStandby7?: string;
  creditCode?: string;
  sfskfq?: string;
  isCreate?: string;
  jgsyCodeOld?: string;
  jgsyIfzssydw?: string;
  jgsyBzsycj?: string;
}

export type JgsyCommonCreationAttributes = JgsyCommonAttributes;

export class JgsyCommon extends Model<JgsyCommonAttributes, JgsyCommonCreationAttributes> implements JgsyCommonAttributes {
  jgsyCode!: string;
  jgsyParentCode?: string;
  depCode?: string;
  jgsyName?: string;
  jgsyType?: string;
  jgsyParentType?: string;
  jgsySystemCode?: string;
  jgsyStates?: string;
  jgsyChildrensum?: number;
  jgsyCodeOrder?: string;
  updateTime?: Date;
  chexiaoTime?: string;
  chexiaoWh?: string;
  chexiaoSystemTime?: string;
  edition?: number;
  updateUnit?: string;
  jgsyStandby1?: string;
  jgsyStandby2?: string;
  jgsyIfvertical?: string;
  jgsyRysbfs?: string;
  jgsySzbm?: string;
  jgsyCheckstate?: number;
  jgsyIfczglbm?: string;
  jgsyIfzfjg?: string;
  chexiaoYy?: string;
  ifShenpi?: string;
  jgbzId?: string;
  jgsyChaojg?: string;
  jgsyChaobz?: string;
  jgsyChaozs?: string;
  jgsyStandby3?: string;
  jgsyStandby4?: string;
  jgsyStandby5?: string;
  jgsyStandby6?: string;
  jgsyStandby7?: string;
  creditCode?: string;
  sfskfq?: string;
  isCreate?: string;
  jgsyCodeOld?: string;
  jgsyIfzssydw?: string;
  jgsyBzsycj?: string;


  static initModel(sequelize: Sequelize.Sequelize): typeof JgsyCommon {
    JgsyCommon.init({
    jgsyCode: {
      type: DataTypes.STRING(100),
      allowNull: false,
      field: 'jgsy_code'
    },
    jgsyParentCode: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_parent_code'
    },
    depCode: {
      type: DataTypes.STRING(6),
      allowNull: true,
      field: 'dep_code'
    },
    jgsyName: {
      type: DataTypes.STRING(200),
      allowNull: true,
      field: 'jgsy_name'
    },
    jgsyType: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_type'
    },
    jgsyParentType: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_parent_type'
    },
    jgsySystemCode: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_system_code'
    },
    jgsyStates: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_states'
    },
    jgsyChildrensum: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      field: 'jgsy_childrensum'
    },
    jgsyCodeOrder: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_code_order'
    },
    updateTime: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'update_time'
    },
    chexiaoTime: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      field: 'chexiao_time'
    },
    chexiaoWh: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'chexiao_wh'
    },
    chexiaoSystemTime: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      field: 'chexiao_system_time'
    },
    edition: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0
    },
    updateUnit: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'update_unit'
    },
    jgsyStandby1: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby1'
    },
    jgsyStandby2: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby2'
    },
    jgsyIfvertical: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifvertical'
    },
    jgsyRysbfs: {
      type: DataTypes.STRING(2),
      allowNull: true,
      defaultValue: "1",
      field: 'jgsy_rysbfs'
    },
    jgsySzbm: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_szbm'
    },
    jgsyCheckstate: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      field: 'jgsy_checkstate'
    },
    jgsyIfczglbm: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifczglbm'
    },
    jgsyIfzfjg: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifzfjg'
    },
    chexiaoYy: {
      type: DataTypes.STRING(32),
      allowNull: true,
      field: 'chexiao_yy'
    },
    ifShenpi: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'if_shenpi'
    },
    jgbzId: {
      type: DataTypes.STRING(32),
      allowNull: true,
      field: 'jgbz_id'
    },
    jgsyChaojg: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaojg'
    },
    jgsyChaobz: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaobz'
    },
    jgsyChaozs: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaozs'
    },
    jgsyStandby3: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby3'
    },
    jgsyStandby4: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby4'
    },
    jgsyStandby5: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby5'
    },
    jgsyStandby6: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby6'
    },
    jgsyStandby7: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby7'
    },
    creditCode: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'credit_code'
    },
    sfskfq: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0"
    },
    isCreate: {
      type: DataTypes.STRING(10),
      allowNull: true,
      field: 'is_create'
    },
    jgsyCodeOld: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_code_old'
    },
    jgsyIfzssydw: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'JGSY_IFZSSYDW'
    },
    jgsyBzsycj: {
      type: DataTypes.STRING(8),
      allowNull: true,
      field: 'jgsy_bzsycj'
    }
  }, {
    sequelize,
    tableName: 'JGSY_COMMON',
    timestamps: false
  });
  return JgsyCommon;
  }
}`

findAll code:

`const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: sqlitePath,
});
const models = initModels(sequelize);
Object.values(models).forEach((model) => {
   model.removeAttribute('id');
});

await models.JgsyCommon.findAll()`

**Comment by steveschmitt** [comment]
Hmm.  I'm not sure about the `dataValues` problem, but I see another issue: `jgsyCode` should be marked with `primaryKey: true` in the model, because you have `CONSTRAINT SYS_PK_12328 PRIMARY KEY (JGSY_CODE)` in the table.  

Maybe that is related somehow.  I'll see if I can reproduce the problem.

**Comment by steveschmitt** [comment]
I used your table create script, then exported the model, and my `jgsy_common.ts` model output looks like this.
 _(I've replaced some fields with `//...` before I pasted it here, just to make the text shorter)_:
```js
import Sequelize, { DataTypes, Model, Optional } from 'sequelize';

export interface JgsyCommonAttributes {
  jgsyCode: string;
  jgsyParentCode?: string;
  depCode?: string;
//...
  jgsyBzsycj?: string;
}

export type JgsyCommonPk = "jgsyCode";
export type JgsyCommonId = JgsyCommon[JgsyCommonPk];
export type JgsyCommonCreationAttributes = Optional<JgsyCommonAttributes, JgsyCommonPk>;

export class JgsyCommon extends Model<JgsyCommonAttributes, JgsyCommonCreationAttributes> implements JgsyCommonAttributes {
  jgsyCode!: string;
  jgsyParentCode?: string;
  depCode?: string;
//...
  jgsyBzsycj?: string;


  static initModel(sequelize: Sequelize.Sequelize): typeof JgsyCommon {
    JgsyCommon.init({
    jgsyCode: {
      type: DataTypes.STRING(100),
      allowNull: false,
      primaryKey: true,
      unique: true,
      field: 'JGSY_CODE'
    },
    jgsyParentCode: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'JGSY_PARENT_CODE'
    },
    depCode: {
      type: DataTypes.STRING(6),
      allowNull: true,
      field: 'DEP_CODE'
    },
//...
    jgsyBzsycj: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_bzsycj'
    }
  }, {
    sequelize,
    tableName: 'JGSY_COMMON',
    timestamps: false,
    indexes: [
      {
        name: "sqlite_autoindex_JGSY_COMMON_1",
        unique: true,
        fields: [
          { name: "JGSY_CODE" },
        ]
      },
      {
        name: "SYS_IDX_SYS_PK_12328_12329",
        unique: true,
        fields: [
          { name: "JGSY_CODE" },
        ]
      },
    ]
  });
  return JgsyCommon;
  }
}
```
Notice how `jgsyCode` has `primaryKey: true` and that the `indexes` are listed at the bottom?  
Your output should also have these.

**Comment by dengzikun** [comment]
@steveschmitt  Thank you!

This is a leagcy database. It has many tables without primary key. The table definition sql was exported by dbeaver.
I found if the JgsyCommon not implements the JgsyCommonAttributes, the dataValues is ok.

`export class JgsyCommon extends Model<JgsyCommonAttributes, JgsyCommonCreationAttributes> {
  
  static initModel(sequelize: Sequelize.Sequelize): typeof JgsyCommon {
    JgsyCommon.init({
    jgsyCode: {
      type: DataTypes.STRING(100),
      allowNull: false,
      field: 'jgsy_code'
    },
    jgsyParentCode: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_parent_code'
    },
    depCode: {
      type: DataTypes.STRING(6),
      allowNull: true,
      field: 'dep_code'
    },
    jgsyName: {
      type: DataTypes.STRING(200),
      allowNull: true,
      field: 'jgsy_name'
    },
    jgsyType: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_type'
    },
    jgsyParentType: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_parent_type'
    },
    jgsySystemCode: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_system_code'
    },
    jgsyStates: {
      type: DataTypes.STRING(2),
      allowNull: true,
      field: 'jgsy_states'
    },
    jgsyChildrensum: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      field: 'jgsy_childrensum'
    },
    jgsyCodeOrder: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_code_order'
    },
    updateTime: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'update_time'
    },
    chexiaoTime: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      field: 'chexiao_time'
    },
    chexiaoWh: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'chexiao_wh'
    },
    chexiaoSystemTime: {
      type: DataTypes.DATEONLY,
      allowNull: true,
      field: 'chexiao_system_time'
    },
    edition: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0
    },
    updateUnit: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'update_unit'
    },
    jgsyStandby1: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby1'
    },
    jgsyStandby2: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby2'
    },
    jgsyIfvertical: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifvertical'
    },
    jgsyRysbfs: {
      type: DataTypes.STRING(2),
      allowNull: true,
      defaultValue: "1",
      field: 'jgsy_rysbfs'
    },
    jgsySzbm: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_szbm'
    },
    jgsyCheckstate: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0,
      field: 'jgsy_checkstate'
    },
    jgsyIfczglbm: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifczglbm'
    },
    jgsyIfzfjg: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0",
      field: 'jgsy_ifzfjg'
    },
    chexiaoYy: {
      type: DataTypes.STRING(32),
      allowNull: true,
      field: 'chexiao_yy'
    },
    ifShenpi: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'if_shenpi'
    },
    jgbzId: {
      type: DataTypes.STRING(32),
      allowNull: true,
      field: 'jgbz_id'
    },
    jgsyChaojg: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaojg'
    },
    jgsyChaobz: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaobz'
    },
    jgsyChaozs: {
      type: DataTypes.STRING(1),
      allowNull: true,
      field: 'jgsy_chaozs'
    },
    jgsyStandby3: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby3'
    },
    jgsyStandby4: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby4'
    },
    jgsyStandby5: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby5'
    },
    jgsyStandby6: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby6'
    },
    jgsyStandby7: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_standby7'
    },
    creditCode: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'credit_code'
    },
    sfskfq: {
      type: DataTypes.STRING(1),
      allowNull: true,
      defaultValue: "0"
    },
    isCreate: {
      type: DataTypes.STRING(10),
      allowNull: true,
      field: 'is_create'
    },
    jgsyCodeOld: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'jgsy_code_old'
    },
    jgsyIfzssydw: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'JGSY_IFZSSYDW'
    },
    jgsyBzsycj: {
      type: DataTypes.STRING(8),
      allowNull: true,
      field: 'jgsy_bzsycj'
    }
  }, {
    sequelize,
    tableName: 'JGSY_COMMON',
    timestamps: false
  });
  return JgsyCommon;
  }
}`

**Comment by dengzikun** [comment]
If add `primaryKey `and `indexes `to the `JgsyCommon`, the field `jgsyCode` of `dataValues` is correct.
But other fields are still undefined.

**Comment by steveschmitt** [comment]
Strange.  If you log the sql query, is it selecting all the columns from the database?

**Comment by dengzikun** [comment]
```SELECT `jgsy_code` AS `jgsyCode`, `jgsy_parent_code` AS `jgsyParentCode`, `dep_code` AS `depCode`, `jgsy_name` AS `jgsyName`, `jgsy_type` AS `jgsyType`, `jgsy_parent_type` AS `jgsyParentType`, `jgsy_system_code` AS `jgsySystemCode`, `jgsy_states` AS `jgsyStates`, `jgsy_childrensum` AS `jgsyChildrensum`, `jgsy_code_order` AS `jgsyCodeOrder`, `update_time` AS `updateTime`, `chexiao_time` AS `chexiaoTime`, `chexiao_wh` AS `chexiaoWh`, `chexiao_system_time` AS `chexiaoSystemTime`, `edition`, `update_unit` AS `updateUnit`, `jgsy_standby1` AS `jgsyStandby1`, `jgsy_standby2` AS `jgsyStandby2`, `jgsy_ifvertical` AS `jgsyIfvertical`, `jgsy_rysbfs` AS `jgsyRysbfs`, `jgsy_szbm` AS `jgsySzbm`, `jgsy_checkstate` AS `jgsyCheckstate`, `jgsy_ifczglbm` AS `jgsyIfczglbm`, `jgsy_ifzfjg` AS `jgsyIfzfjg`, `chexiao_yy` AS `chexiaoYy`, `if_shenpi` AS `ifShenpi`, `jgbz_id` AS `jgbzId`, `jgsy_chaojg` AS `jgsyChaojg`, `jgsy_chaobz` AS `jgsyChaobz`, `jgsy_chaozs` AS `jgsyChaozs`, `jgsy_standby3` AS `jgsyStandby3`, `jgsy_standby4` AS `jgsyStandby4`, `jgsy_standby5` AS `jgsyStandby5`, `jgsy_standby6` AS `jgsyStandby6`, `jgsy_standby7` AS `jgsyStandby7`, `credit_code` AS `creditCode`, `sfskfq`, `is_create` AS `isCreate`, `jgsy_code_old` AS `jgsyCodeOld`, `JGSY_IFZSSYDW` AS `jgsyIfzssydw`, `jgsy_bzsycj` AS `jgsyBzsycj` FROM `JGSY_COMMON` AS `JgsyCommon` ORDER BY `JgsyCommon`.`jgsy_code` ASC;```

**Comment by dengzikun** [comment]
I'm not sure the issue is related to the `_changed` field.

![image](https://user-images.githubusercontent.com/16617559/107742983-06439800-6d4b-11eb-82d2-29c58e02d3ac.png)

The `JgsyCommon `not implements the `JgsyCommonAttributes`: 

![image](https://user-images.githubusercontent.com/16617559/107743570-1314bb80-6d4c-11eb-8578-c5040e579fe8.png)

**Comment by dengzikun** [comment]
[https://github.com/sequelize/sequelize/issues/10579](https://github.com/sequelize/sequelize/issues/10579)

**Comment by cchyung** [comment]
Is there any further update to this issue?  See that there's an issue with a babel plugin, but if we want to use sequelize-auto can we still use typescript?

**Comment by steveschmitt** [comment]
I'm not sure where the problem lies.  The sequelize-auto output is supposed to conform to the TypeScript recommendations from the [Sequelize docs](https://sequelize.org/master/manual/typescript.html).

If we need to change the TypeScript output, we can do that.  But right now I don't know what to change.
