### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by awcchungster** [sequelize/sequelize-auto#507]
Hi @steveschmitt! Thanks for all your hard working maintaining the project and answering questions. Is there a company backing this repo, or is this individually done? If the latter, how do I donate?

**Comment by steveschmitt** [comment]
Thanks @awcchungster! There's no company backing **sequelize-auto**.  The main **sequelize** project may have some backing, but I don't know much about it.  And I'm not set up to receive donations.

When I first tried to use **sequelize-auto**, it had a lot of bugs, and I considered looking elsewhere.  But I came across #398 and decided to become a maintainer.  I work on it in my free time when I'm not busy on projects for [IdeaBlade](http://ideablade.com).
