### ISSUE TITLE
nvarchar(max) should be treated as TEXT not string

### ISSUE THREAD

**Issue by bensilo** [sequelize/sequelize-auto#508]
Sequelize treats DataTypes.TEXT as unlimited length string whereas it treats DataTypes.STRING as limited length string (default length 255 characters, and possibly a max of 4000 characters).

Could we generate DataTypes.TEXT instead of DataTypes.STRING for nvarchar(max) by adding the following 3 lines into auto-generator.js from about line 418:

        }
        // ********************* START OF CODE TO ADD
        else if (type === 'nvarchar(max)' || type === 'varchar(max)') {
            val = 'DataTypes.TEXT';
        }
        // ********************* END OF CODE TO ADD
        else if (type.match(/n?varchar|string|varying/)) {
            val = 'DataTypes.STRING' + (!lodash_1.default.isNull(length) ? length : '');
        }

Microsoft recommends nvarchar(max) over text type. Hence I would like to use nvarchar(max) on the table and have it treated as TEXT by Sequelize.

**Comment by steveschmitt** [comment]
Yes, that makes sense.  It'll be in the next release.  

Thanks for the suggestion.

**Comment by bensilo** [comment]
Excellent - thanks Steve.

**Comment by steveschmitt** [comment]
Fixed in 0.8.2
