### ISSUE TITLE
Duplicate identifiers when generating models that have the same singular and plural words

### ISSUE THREAD

**Issue by darrendlin** [sequelize/sequelize-auto#509]
sequelize-auto pluralizes words using sequelize's util library which uses the [`pluralize` function](https://github.com/sequelize/sequelize/blob/9634338d8f9a07ff151f70a91793b37547e2c23e/lib/utils.js#L112) from the [node-inflection library](https://github.com/dreamerslab/node.inflection).

Specifically, I'm referring to https://github.com/sequelize/sequelize-auto/blob/89a2e0e96ca1087c8597cd94d3bfd1b0609b3c2b/src/auto-generator.ts#L574

If a word's singular and plural form is the same, then sequelize-auto ends up generating a bunch of variables that share the same name (but different types).

![](https://cdn.discordapp.com/attachments/820076472186044446/821112409514704917/unknown.png)

This is obviously not ideal.

I've dug through some issues on the sequelize repo and found https://github.com/sequelize/sequelize/issues/7562#issuecomment-312770176 which suggested configuring my own inflection functions for certain words. Is this possible with sequelize-auto or is there a different workaround?

**Comment by steveschmitt** [comment]
Ugh, plurals again!  English language is the worst! :)

There's currently no way to specify your own function in sequelize-auto.  If there was, what would you do for `transportation` ?

A simpler change (to the sequelize-auto code), would be to add "s" to the end of the plural name **if** the plural is the same as the singular.

In your example, that would give you `transportations`.  We could also end up with `baggages`, `furnitures`, `offsprings`, `staffs`, etc.  Is that acceptable?

**Comment by darrendlin** [comment]
Yes, I'm much more okay with breaking English rules than to need to write something to manually change this every time I want to sequelize-auto something 😂

**Comment by steveschmitt** [comment]
Fixed in 0.8.2
