### ISSUE TITLE
Associations (mixins) not getting generated in Typescript models

### ISSUE THREAD

**Issue by JeongJuhyeon** [sequelize/sequelize-auto#512]
https://github.com/sequelize/sequelize-auto/issues/452#issuecomment-739318314

Here it says that they should be getting generated since 0.7.5, but I'm not seeing this.

sequelize-auto: 0.8.1
sequelize: 6.6.2
typescript: 4.2.3
MariaDB

Example generated model:

```
export class file extends Model<fileAttributes, fileAttributes> implements fileAttributes {
  file_id?: string;
  path?: string;
  original_name?: string;
  extension?: string;
  size?: string;
  uploader?: string;
  file_folder_id?: string;
  date_create?: Date;
  checksum?: string;

  static initModel(sequelize: Sequelize) {
....
```
uploader and file_folder_id are both foreign keys here.

**Comment by steveschmitt** [comment]
Fixed in 0.8.2
