### ISSUE TITLE
tinyint(1) to boolean

### ISSUE THREAD

**Issue by joyceHong0524** [sequelize/sequelize-auto#514]
"sequelize-auto": "^0.7.10",
        "mysql2": "^2.2.5",

I am working on my project and having a problem that sequelize-auto generates model with tinyint which is supposed to be boolean. Do I need to manually change tinyint to boolean (which i think fades the purpose of using sequelize-auto)?

Thanks for this amazingly useful library tho

**Comment by steveschmitt** [comment]
Fixed in 0.8.2

**Comment by joyceHong0524** [comment]
@steveschmitt 
seems like it has not been released yet. (lastest version is 0.8.1 as far as I know)
Should I wait for it to import to my project?

**Comment by steveschmitt** [comment]
I just published 0.8.2, so it should show up in npm soon.

https://www.npmjs.com/package/sequelize-auto
