### ISSUE TITLE
Add option to remove alias from cli

### ISSUE THREAD

**Issue by FluxusGaming** [sequelize/sequelize-auto#515]
To avoid EagerLoadingError [SequelizeEagerLoadingError]: users is associated to user_coins using an alias. You must use the 'as' keyword to specify the alias within your include statement.

**Comment by sinkingtitanic** [comment]
> etter is if we could generate the alias only when absolutely necessary.

Do you mind if I add the flag a perform a pull request?

**Comment by steveschmitt** [comment]
Added `--noAlias` in 0.8.3

**Comment by FluxusGaming** [comment]
Hi, I tried the new --noAlias option and it still generates the aliases in the model, init-models.js. Any solution? Currently I have to delete them by hand one by one all the as: "".

EagerLoadingError [SequelizeEagerLoadingError]: teachers is associated to teachers_rooms using an alias. You must use the 'as' keyword to specify the alias within your include statement.

**Comment by steveschmitt** [comment]
Fixed in 0.8.4
