### ISSUE TITLE
underscored is set, but it has no effect

### ISSUE THREAD

**Issue by jsicu** [sequelize/sequelize-auto#518]
### underscored is set, but it has no effect. 

**Run**
```
sequelize-auto -h localhost -d koa2_server -u root -x password -p 3306 -o ./db/models -e mysql -a ./config/db.json
```

**Generated user  model**
```
const Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('user', {
    id: {
      type: DataTypes.STRING(64),
      allowNull: false,
      primaryKey: true
    },
    user_name: {
      type: DataTypes.STRING(255),
      allowNull: false,
      unique: "user_name"
    },
    password: {
      type: DataTypes.STRING(255),
      allowNull: false
    },
    is_cancel: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: 0
    },
    create_time: {
      type: DataTypes.DATE,
      allowNull: false
    },
    update_time: {
      type: DataTypes.DATE,
      allowNull: false
    },
    delete_time: {
      type: DataTypes.DATE,
      allowNull: true
    }
  }, {
    sequelize,
    tableName: 'user',
    timestamps: true,
    underscored: true,
    indexes: [
      {
        name: "PRIMARY",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "id" },
        ]
      },
      {
        name: "id",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "id" },
        ]
      },
      {
        name: "user_name",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "user_name" },
        ]
      },
    ]
  });
};

```

**db.json**
```
{
  "timestamps": true,
  "underscored": true
}
```

**The correct query should look like this：** SELECT `id`, `user_name` AS `userName`, `password`, `is_cancel` AS `isCancel`, `create_time` AS `createTime`, `update_time` AS `updateTime`, `delete_time` AS `deleteTime` FROM `user` AS `user` WHERE (`user`.`delete_time` IS NULL AND (`user`.`password` = 'xxx' AND `user`.`user_name` = 'admin' AND `user`.`is_cancel` = 0));
**But it is：** SELECT `id`, `user_name`, `password`, `is_cancel`, `create_time`, `update_time`, `delete_time`, `create_time` AS `createTime`, `update_time` AS `updateTime`, `delete_time` AS `deleteTime` FROM `user` AS `user` WHERE (`user`.`delete_time` IS NULL AND (`user`.`userName` = 'admin' AND `user`.`password` = 'xxx' AND `user`.`isCancel` = 0));

**So SQL reports an error：** "Unknown column 'user.userName' in 'where clause'"

Is it that I set it wrong or is sequelize-auto just like this

**Comment by steveschmitt** [comment]
Try adding `--caseProp c` to the sequelize-auto command line.

**Comment by jsicu** [comment]
nice！！！！！
