### ISSUE TITLE
Need option to disable generating init-models

### ISSUE THREAD

**Issue by Rc85** [sequelize/sequelize-auto#519]
I am generating my models based on schema so that the output of a model goes into its own schema folder. However, if there are associations to another schema, it causes error on the import because it looks for the file in the same folder.

Consider a restaurant has many locations and restaurant is in the `restaurant` schema and locations are in the `location` schema. The folder structure would look like this

```
restaurant/restaurants.ts
location/locations.ts
```
Inside `locations.ts`, it would import the restaurant ID from `./restaurants.ts', which it does not exist.

This is mostly very frustrating when it is in the `init-models` file because every time I generate a model of a new table, the `init-models` file gets replaced with only the model I am generated. This causes problems because I have to fix the import every time and all the other tables/models are gone and for TS developers, TS config will throw error on compilation even if `init-models` is not being used.

**Comment by steveschmitt** [comment]
Added `--noInitModels` in 0.8.3
