### ISSUE TITLE
Problem with alias "name_table" in two separate associations.

### ISSUE THREAD

**Issue by IlyaIvanchikov** [sequelize/sequelize-auto#520]
![image](https://user-images.githubusercontent.com/47752532/116085843-e7954200-a6a7-11eb-8f42-fa32e14439f7.png)

### I read a lot about this problem, but all solutions weren't what I need. I started to research repository and understood, that my problem doesn't process, and in my opinion it is bug.
Simpler will be speak about this problem on example.
***
I have next models:
- cities
- transports
- allow_cities

All not needed fields I skipped. Only describing problem!
In model **transports** i have connections with model **cities** -> **belongsTo**, therefore i have **alias "as: transport**. 
Then i make model called **allow_cities** (many to many) where i have 2 fileds city_id and **transport_id** then sequelize-auto generate again alias **transport** for fields called **transport**, which relates to model **allow_cities**, because of it I get error on image above.
I added additional condition in **if**, and my problem disappeared. Other generation aliases didn't suffer #521

**Comment by IlyaIvanchikov** [comment]
> # #![image](https://user-images.githubusercontent.com/47752532/116085843-e7954200-a6a7-11eb-8f42-fa32e14439f7.png)
> ### I read a lot about this problem, but all solutions weren't what I need. I started to research repository and understood, that my problem doesn't process, and in my opinion it is bug.
> Simpler will be speak about this problem on example.
> 
> I have next models:
> 
> * cities
> * transports
> * allow_cities
> 
> All not needed fields I skipped. Only describing problem!
> In model **transports** i have connections with model **cities** -> **belongsTo**, therefore i have **alias "as: transport**.
> Then i make model called **allow_cities** (many to many) where i have 2 fileds city_id and **transport_id** then sequelize-auto generate again alias **transport** for fields called **transport**, which relates to model **allow_cities**, because of it I get error on image above.
> I added additional condition in **if**, and my problem disappeared. Other generation aliases didn't suffer

**Comment by steveschmitt** [comment]
We will keep this open until the fixed version is released.

**Comment by steveschmitt** [comment]
Fixed in 0.8.3
