### ISSUE TITLE
Paranoid Problem

### ISSUE THREAD

**Issue by vivianeflowt** [sequelize/sequelize-auto#529]
As I understand if I pass paranoid=true inside additional it should put this attribute on each model, but that's not happening. Does anyone know why?

**Comment by steveschmitt** [comment]
That _should_ work.  Sounds like it might be a bug.

**Comment by Karbust** [comment]
I'm facing the same issue, any idea on how to fix it?

**Comment by TooBug** [comment]
Facing the same issue. Any update on this?

**Comment by steveschmitt** [comment]
Fixed in 0.8.4
