### ISSUE TITLE
PostgreSql TypeScript (types BYTEA, inet, oid, zson)

### ISSUE THREAD

**Issue by Sicdex** [sequelize/sequelize-auto#534]
Hi, i ran into a problem while creating typescript models and (PostgreSql).
Official page sequelize: [https://sequelize.org/v5/manual/data-types.html](url) has type support BYTEA, inet.

[Official page sequelize types](https://sequelize.org/v5/manual/data-types.html) 

1). [Image](https://i.imgur.com/28gDgxw.png)
2). [Image](https://i.imgur.com/bLbdGE4.png)
3). [Image](https://i.imgur.com/Fldooq8.png)
4). [My console](https://i.imgur.com/LIPgQBH.png)

P.S
this error ? [(Image)](https://i.imgur.com/leFByso.png), not found for me

**Comment by steveschmitt** [comment]
It seems we need `DataTypes.BLOB` for **BYTEA**, and `DataTypes.INET` for **inet**.  What should the TypeScript types be for these?

What DataTypes should we use for **oid** and **zson** ?

**Comment by Sicdex** [comment]
> It seems we need `DataTypes.BLOB` for **BYTEA**, and `DataTypes.INET` for **inet**. What should the TypeScript types be for these?
> 
> What DataTypes should we use for **oid** and **zson** ?

I didn't find a solution for the types "zson" and "oid" in the typescript and I was wrong. But "zson" is equal to "json" and it looks like these types will remain "any". See the last image generated with error, my settings defualt for postgressql  "(floor(((random() * (62)::double precision) + (2)::double precision)))::integer"
type "smallint"

**Comment by steveschmitt** [comment]
Can you please put text in these comments, instead of images?

**Comment by Sicdex** [comment]
> Can you please put text in these comments, instead of images?

```
private_ip_ending: {
    type: DataTypes.SMALLINT,
    allowNull: false,
    defaultValue: floorrandom * 62
}
```

**Comment by steveschmitt** [comment]
Added types in 0.8.4
