### ISSUE TITLE
*beginner* No idea how to import models and then to use them in express app with routes

### ISSUE THREAD

**Issue by niemiaszek** [sequelize/sequelize-auto#538]
Hello, I am making my first web using node with express, sequelize and your sequelize-auto since I already had mysql database prepared.

At first i tried in my index.js file:
```
const express = require("express");
const app = express();
const cors = require("cors");
var db = require("./models");

app.use(express.json());
app.use(cors());

const ebookRouter= require("./routes/ebook");
app.use("/ebook", ebookRouter);
```

Then in every route, f.e ./routes/ebook.js I would do:

```
const express = require("express");
const router = express.Router();
const { ebook } = require("../models");
router.get("/", async (req, res) => {
  const listOf_ebooks = await ebook.findAll();
  res.json(listOf_ebooks);
});
```

This was the way I've seen in [Pedro Machado tutorial for sequelize](https://github.com/machadop1407/FullStack-Course/tree/Episode5/server). Everything worked till I tried to use associations. I assume they were not loaded, since I didn't really use init-models.js.

So I tried to follow your sample-es5.js, and I menaged to get associations working, but only in my index.js file. I have no idea, how to make it work in my route files.

In my index.js file I did:
```
var Sequelize = require("sequelize");
var initModels = require("./models/init-models");

var config = require("./config/config");
const router = express.Router();
var sequelize = new Sequelize(
  config.dbname,
  config.user,
  config.pass,
  config.options
);
var models = initModels(sequelize);
var ebook = models.ebook;
```
What  should I do then in my routes fiels?

**Comment by niemiaszek** [comment]
Hello. I resolved my problem. All it takes is to combine both solutions (sample and Pedros one), so:
```
const db = require("./models");
var initModels = require("./models/init-models");
var models = initModels(db.sequelize);
db.sequelize.sync().then(() => {
  app.listen(3001, () => {
    console.log("Server running on port 3001...");
  });
});
```
It might be nothing special/new for you, but for me as a beginner it took a moment to notice that i should use initModels(db.sequelize) instead of creating new Sequelize just as in sample. Could you modify README with more clear instructions even for beginners?

**Comment by steveschmitt** [comment]
I agree that we need more instructions and examples.  It will be hard to cover each person's idea of the correct app structure though.
