### ISSUE TITLE
Useful to have a javascript in addition to a command line API

### ISSUE THREAD

**Issue by johnlabarge** [sequelize/sequelize-auto#54]
I actually run this as a grunt task.  Instead of spawning, it wouldn't suck to be able to call this directly from javascript. 

Thoughts?

**Comment by durango** [comment]
I don't see why you couldn't

https://github.com/sequelize/sequelize-auto/blob/master/bin/sequelize-auto#L50-L56

**Comment by johnlabarge** [comment]
In my case I may need to add default values to the fields since I'm working with an existing database.  For example, I need to add default values for created_at and updated_at or prevent them from being null on findOrCreate or is there another way to do that?

**Comment by durango** [comment]
Are there default values setup on your database already for those fields? I can look into separating out the functionality of scraping + building (which I obviously should have done in the beginning). If those fields do have specific default values, which DBMS are you using and what are the default values?

**Comment by johnlabarge** [comment]
It turns out that there is no default.  The db I'm scraping is a rails managed db.  I am using sequelize to inject data that is collected from a different application.

**Comment by Sawtaytoes** [comment]
I would like this as well. For me, auto-genning the models is going to be super useful if I don't want to include them in my repo. Also, it's nice to use env vars for DB credentials when I'm already using them for Sequelize's connection.
