### ISSUE TITLE
[Suggestion] custom indentation

### ISSUE THREAD

**Issue by Datzu712** [sequelize/sequelize-auto#561]
Maybe can be a good idea if i can tell to the sequelize-auto the level of indentation to use, because i use 4 spaces and the sequelize-auto made the models with spaces 2.

**Comment by steveschmitt** [comment]
Actually, there's already an `indentation` option if you use the [programmatic api](https://github.com/sequelize/sequelize-auto#programmatic-api).  We should make it a command-line option also.

**Comment by steveschmitt** [comment]
Fixed in sequelize-auto@0.8.7
