### ISSUE TITLE
Issues with table names that are JavaScript reserved words

### ISSUE THREAD

**Issue by MariusKarthaus** [sequelize/sequelize-auto#562]
To keep track of which device is plugged into a certain port of a certain switch in the network, we have a table called 'switch'. This caused sequelize-auto to generate non-working code, which is to be expected.  I've found that a table called 'var' will cause similar problems, so it is probably an issue with all JavaScript reserved words that are valid table names. I expect that having a table called 'Model' will also cause a problem with that being variable name in the same scope etc.

I'd like to suggest throwing a warning at generation time, and documenting that this will cause a problem. Also some documentation on how to work around table names like that could help out people encountering this issue.

**Comment by steveschmitt** [comment]
Fixed in sequelize-auto@0.8.7
