### ISSUE TITLE
Id field name is not explicit

### ISSUE THREAD

**Issue by kfontaine-smartwave** [sequelize/sequelize-auto#571]
When generating a model for table `Entity` with a primary key field named `EntityId`, the field does not include an explicit `field` attribute.

When Sequelize try to use the model, the column is queried with name `entity_id`, leading to a column not existing error.

Proposed solution : 
Always generate field name, event for Id column.

Specific environnement : mssql, but the problem might exist on other DB.

**Comment by steveschmitt** [comment]
Thanks, I'll take a look.

**Comment by kfontaine-smartwave** [comment]
I will try to submit a PR if possible.

**Comment by steveschmitt** [comment]
Fixed in sequelize-auto@0.8.7

**Comment by kfontaine-smartwave** [comment]
Thank you very much for the fix !
