### ISSUE TITLE
useDefine is not working

### ISSUE THREAD

**Issue by vishnup95** [sequelize/sequelize-auto#573]
Hey, first off thanks for the super cool package. Saves a lot of time. I am trying to generate models using the below cli command for my local db

`sequelize-auto -o "./models" -l esm -d [db_name] -h localhost --caseModel c --caseProp c -u root -p 3306 -x [password] -e mysql --useDefine`

The config options I get after running this (the next log in the terminal) 
```
 {
  spaces: true,
  indentation: 2,
  directory: './models',
  additional: {},
  dialect: 'mysql',
  port: 3306,
  host: 'localhost',
  database: '***',
  storage: '****',
  tables: null,
  skipTables: null,
  skipFields: null,
  pkSuffixes: null,
  schema: undefined,
  lang: 'esm',
  caseModel: 'c',
  caseFile: 'o',
  caseProp: 'c',
  noAlias: false,
  noInitModels: false,
  noWrite: false,
  views: false,
  singularize: false,
  username: 'root'
}

```
All my models are still generated using static. I checked the version and I am running v0.85.0. Am I missing something?

**Comment by steveschmitt** [comment]
I'm missing something - I haven't released the version that has `useDefine` in it yet!

**Comment by vishnu-wednesday** [comment]
That's weird. Do you think you could create a new release with useDefine included. Would be a nice addition.

**Comment by vishnup95** [comment]
That's weird. Do you think we could have a new release with useDefine included then. What are you missing? Would be a nice addition.

**Comment by steveschmitt** [comment]
Well, I was going to try to pack in some other features and fixes for the next release, but haven't had time.

**Comment by steveschmitt** [comment]
The `useDefine` option is in release 0.8.6, just pushed to npm.

And you get to be the first to use it.

**Comment by vishnup95** [comment]
Thanks for the quick turn around and responses.  Closing this!
