### ISSUE TITLE
Doesn't work with belongsTo when non-standard foreign keys are present

### ISSUE THREAD

**Issue by Sawtaytoes** [sequelize/sequelize-auto#61]
If I have a DB with a table `accounts` but in another section, a badly-named foreign key `userid` tracking back to it, the generator does account for this when making the column reference in the define statement, but if I manually add `belongsTo`, it does not do this and instead looks for `accountId`.

Is this something I'm supposed to handle or can the generator do that for me?
Might be similar to https://github.com/sequelize/sequelize-auto/issues/34

**Comment by steveschmitt** [comment]
Added `belongsTo/hasOne/hasMany` to the `initModels` function in release **0.7.0**.
