### ISSUE TITLE
New dialects in sequelize 6.x break the ts build in sequelize-auto

### ISSUE THREAD

**Issue by hhowe29** [sequelize/sequelize-auto#641]
On 03/11/23, a fresh clone of the repo fails to build with this error

```bash
$ npm run tsc

> sequelize-auto@0.8.7 tsc
> tsc

src/dialects/dialects.ts:8:14 - error TS2739: Type 
'{ mssql: DialectOptions; mysql: DialectOptions; mariadb: DialectOptions; postgres: DialectOptions; sqlite: DialectOptions; }' 
is missing the following properties from type <snipped> : db2, snowflake, oracle

8 export const dialects: { [name in Dialect]: DialectOptions } = {
```

`npm list sequelize` shows that I pulled in 6.29.3

**Comment by MihirModi1421** [comment]
Hi! I was working on adding Oracle dialect support and ran into this issue. 
Any updates on it? 
I’d be glad to help and can take it on if it’s available.

Note: I’m currently working on Oracle dialect support independently — it’s not officially assigned.
