### ISSUE TITLE
Feature: autoloading the database credentials

### ISSUE THREAD

**Issue by ErikvdVen** [sequelize/sequelize-auto#67]
I think it would be a neat idea to keep below command line even simpler, by autoloading the database configuration, but still being able to enter the credentials manually if you want to:

```
sequelize-auto -o "./models" -d sequelize_auto_test -h localhost -u my_username -p 5432 -x my_password -e postgres
```

I mean like doctrine:

```
php vendor/bin/doctrine orm:schema-tool:create
```

As you can see you don't have to enter the database credentials, cause they're already specified inside the project. Doctrine uses the `config/cli-config.php` file for this:

```
<?php
use Doctrine\ORM\Tools\Console\ConsoleRunner;

// replace with file to your own project bootstrap
require_once 'app/bootstrap.php';

return ConsoleRunner::createHelperSet($entityManager);
?>
```

The above `$entityManager` contains the database connection singleton.

Maybe an idea for the `sequelize-auto`? So it uses the credentials of the current environment by default. Well actually above samples of Doctrine are for creating tables from your models, and not the opposite, but I just want to clarify my idea of autoloading the database configuration.

**Comment by durango** [comment]
You can now specify a config file with the `-c` option, should resolve this issue.
