### ISSUE TITLE
Example command

### ISSUE THREAD

**Issue by MarcorOnline** [sequelize/sequelize-auto#68]
Into the example add "node" at the begging of the command (before sequelize-auto -o "./models" -d sequelize_auto_test -h localhost -u my_username -p 5432 -x my_password -e postgres)

**Comment by durango** [comment]
You shouldn't need to call node before the binary.. that's the point of the global install and the bin path. Are you having some sort of trouble?

**Comment by MarcorOnline** [comment]
On my Windows PC I have some problems with global installation, and I used the "node" command to make it work. This is the reason of my suggestion.

Thanks for your fast reply
