### ISSUE TITLE
table names need adding to models

### ISSUE THREAD

**Issue by nick-sturrock** [sequelize/sequelize-auto#7]
The models generated ok but half the table names were wrong as sequelize-restful does some weird pluralisation on the table names that you can't turn off, meaning that you have to add a declaration

    {
        tableName:'<actual-table-name-rather-than-pluralised-version>'
    }

to most if not all models if you don't use the same pluralisation convention. This is as much a fault with sequelize-restful as it is with the generator but the models could be more strictly generated to match the schema.

**Comment by fourpixels** [comment]
+1

**Comment by dbpolito** [comment]
This should be fixed by https://github.com/sequelize/sequelize-auto/pull/32

**Comment by MJafarMashhadi** [comment]
mmmm, it's not. I used this command to generate models from a sqlite database:

      sequelize-auto --dialect sqlite -o models -d ../db.sqlite -h 127.0.0.1

and sequelize-auto version is 0.2.5 (latest in npm)

**Comment by MJafarMashhadi** [comment]
your pull request (#32) is merged in 0.2.2

**Comment by MJafarMashhadi** [comment]
`freezeTableName: true` should be *always* added to model options. People use sequelize-auto in order to manage an existing schema and data via sequelize, so table names *should* be consistent.
