### ISSUE TITLE
primary composite keys with foreign keys 

### ISSUE THREAD

**Issue by atulhm** [sequelize/sequelize-auto#70]
using mysql.
3 composite key fields
2 of those fields have foreign keys.

the primaryKey attribute is not generated.
Traced the issue to this commit: https://github.com/sequelize/sequelize-auto/commit/54d3753ecff6f347c577f23b9fa7c8aa378c1be6

removing the change fixed my issue, but I'm sure the commit was needed, -- how can I help?

**Comment by durango** [comment]
@atulhm could you paste an export of your SQL schema please? Would help for debugging (don't need the data just the structure).

**Comment by atulhm** [comment]
CREATE TABLE `disreports` (
  `ORGANIZATION_ID` int(11) NOT NULL,
  `COMPANY_ID` int(11) NOT NULL,
  `REPORT_UNAME` varchar(255) NOT NULL,
  `PHYSICAL_NAME` varchar(255) DEFAULT NULL,
  `REPORT_MODULE_UNAME` varchar(50) DEFAULT NULL,
  `MODULE_UNAME` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `PATH` varchar(255) DEFAULT NULL,
  `MENU_LOCATION` varchar(255) DEFAULT NULL,
  `MENU_ORDER` int(11) unsigned DEFAULT '0',
  `DISPLAY_NAME` varchar(255) DEFAULT NULL,
  `IS_ENABLED` bit(1) DEFAULT b'1',
  `DISPLAY_ICON` varchar(255) DEFAULT NULL,
  `CREATE_USER` varchar(100) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(100) DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ORGANIZATION_ID`,`COMPANY_ID`,`REPORT_UNAME`),
  KEY `FK824892D8B2A58288` (`ORGANIZATION_ID`,`COMPANY_ID`),
  CONSTRAINT `FK824892D8B2A58288` FOREIGN KEY (`ORGANIZATION_ID`, `COMPANY_ID`) REFERENCES `cxm_company` (`ORGANIZATION_ID`, `COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by atulhm** [comment]
I've committed  a fix to the mysql bit generation issue on my fork/branch.

**Comment by durango** [comment]
@atulhm try this version please `+ sequelize-auto@0.4.5`

**Comment by atulhm** [comment]
Awesome!  It works.  Thank you!
