### ISSUE TITLE
Generate models with 'timestamps: false"

### ISSUE THREAD

**Issue by pnakibar** [sequelize/sequelize-auto#72]
Here I am working with a database that is already in production and I cant afford to implement the sequelize timestamps (createdat and deletedat). 

I would really like to see a option that gets a *more raw* data from the database, like a --notimestamps. 

Update:
Actually I tried to use the -a flag with the json described bellow, and no luck.
```json
{
  "timestamps": false
}
```

**Comment by pnakibar** [comment]
Somehow now it worked, go figure.

**Comment by durango** [comment]
Glad to that it's working for you.. the additional configs should allow more options for you (`-c/--config`) which you would enter in options within the `define` property of that.

https://sequelize.readthedocs.org/en/latest/api/sequelize/

**Comment by pnakibar** [comment]
Yes, I didn't got how the -c and the -a worked, just got into the code for a minute and understood how it works. Pretty simple. Used the same -a flag with the exactly the same json and it worked.

**Comment by sebastienbarre** [comment]
I have the opposite problem :) I have about 150 MySQL table, and in all of them the `createdAt` field is known as `created` and the `updatedAt` field is known as `modified`. Is there an option that I missed in `sequelize-auto` so that it automatically creates:
```
  sequelize.define(name, { ... }, { createdAt: 'created', updatedAt: modified'});
```
for my 150+ models?
Thank you for the great work.

**Comment by mohamed-badaoui** [comment]
To disable timestamps, just add a config file .sequelize-auto.cfg.js with

`'use strict';

module.exports = {
	timestamps: false
}`

and then execute your sequelize-auto command with options

-a .sequelize-auto.cfg.js

and it should work.
