### ISSUE TITLE
Documentation needs a better tutorial for newbies

### ISSUE THREAD

**Issue by xorbis** [sequelize/sequelize-auto#73]
Hi, I am new to sequelize and sequelize-auto and I was wondering if some questions could be answered and put in the readme.

I used the programmatic API in order to call sequelize-auto and it generates the models properly.
I was wondering since sequelize-auto requires sequelize and uses the connection info in order to generate the models, is there an instance of sequelize somewhere inside my new SequelizeAuto() once run has been called? If so, where is it? And did it import the models?

In the programmatic API section of the README, I've modified like so:

var SequelizeAuto = require('sequelize-auto')
var auto = new SequelizeAuto('database', 'user', 'pass');

auto.run(function (err) {
  if (err) throw err;

  console.log(auto.tables); // table list
  console.log(auto.foreignKeys); // foreign key list

  // Sequelize API call...
  auto.tables["User"].findAll({attributes: ["id", "name"]});
};

Which is not working since tables is only an array describing the model.
Do I need to import the models manually using sequelize?

**Comment by durango** [comment]
> Do I need to import the models manually using sequelize?

Yes, sequelize-auto is explicitly for generating model objects/generic JS template for `sequelize.import` that's all. It's not designed to be a "map my database and then perform the rest of my application" type of program. The reason for the programmatic API is to allow programmers to create their own templates and adjust any explicit modifications as required to each table/column/etc. object.

**Comment by xorbis** [comment]
Thanks for clarifying, so now I will loop import these files and create an instance of sequelize.

**Comment by xorbis** [comment]
FYI: this article describes howto do the same using sequelize-cli.

**Comment by durango** [comment]
Im not sure if I understand your last comment... sequelize-cli does what sequelize-auto does?

**Comment by xorbis** [comment]
I just meant that I can load the models generated by sequelize-auto with the models/index.js that sequelize-cli generates when doing "sequelize init". I think... testing it right now.

**Comment by durango** [comment]
Closing for now, feel free to re-open if you run into any issues.
