### ISSUE TITLE
Char datatype not being used

### ISSUE THREAD

**Issue by mrbarletta** [sequelize/sequelize-auto#74]
Thanks for the great tool :+1:  made my day!

On a mysql DB - CHAR(XX) are not being transformed as DATATYPE.CHAR(XX) but as  CHAR(XX) 

This is causing sequelize-graphql issues when importing the models.

I added this line on index.js +217    
```
else if (_attr.match(/^char/)) {
              var length = _attr.match(/\(\d+\)/);
              val = 'DataTypes.CHAR' + (!  _.isNull(length) ? length : '');
            }
```
And works as (I) expected. 

Is this a real issue or a lack of deep understanding on my part?

Thanks

**Comment by durango** [comment]
Nope that's how it should work, most likely omitted the char datatype originally due to always using varchar (in postgres land there's no real difference internally). Mind sending a PR over? 👍
