### ISSUE TITLE
UUID primary key for MSSQL

### ISSUE THREAD

**Issue by deksden** [sequelize/sequelize-auto#78]
After importing some MS SQL (2008R2) table i have following field definition in my model:
```      
ID: {
     type: 'UNIQUEIDENTIFIER',
     allowNull: false,
     defaultValue: '(newid())',
     primaryKey: true
 }, 
```
Actually, IMHO, it should be like this:
```      
ID: {
     type: DataTypes.UUIDV4,
     allowNull: false,
     primaryKey: true
 }, 
```

P.S. .UUIDV4 makes this field as uuid-type and auto-generate new value for it

**Comment by deksden** [comment]
Here is PR for this feature: https://github.com/sequelize/sequelize-auto/pull/79

**Comment by leolorenzoluis** [comment]
@deksden Producing DataTypes.UUIDV4 breaks SQL Server. Getting an error that column data type UUIDv4 is not found. Changing the DataType to UUID fixes it.

**Comment by deksden** [comment]
Any code/sample? What SQL Server version? 

As for time of that issue 2 yrs ago all was fine with tested SQL server versions

**Comment by loopeverything** [comment]
For anyone else who stumbles across this today, you can keep `UNIQUEIDENTIFIER` (versus `CHAR` with DataTypes.UUID), by doing:
```
id: {
  type: 'UNIQUEIDENTIFIER',
  defaultValue: DataTypes.UUIDV4,
  primaryKey: true
},
```
Just keep the defaultValue as `DataTypes.UUIDV4` versus the literal `newid()` to avoid breaking the model's associations.

**Comment by josuerodcat90** [comment]
> For anyone else who stumbles across this today, you can keep `UNIQUEIDENTIFIER` (versus `CHAR` with DataTypes.UUID), by doing:
> 
> ```
> id: {
>   type: 'UNIQUEIDENTIFIER',
>   defaultValue: DataTypes.UUIDV4,
>   primaryKey: true
> },
> ```
> 
> Just keep the defaultValue as `DataTypes.UUIDV4` versus the literal `newid()` to avoid breaking the model's associations.

Thanks a lot!!!, this worked for me.
