### ISSUE TITLE
Aliases for table names for use as model names

### ISSUE THREAD

**Issue by deksden** [sequelize/sequelize-auto#80]
It would be cool to have ability to define alias for table name to use as model name in import (-t CLI option).

For ex: sequelize-auto .... -t "tbl_Task as Task, tbl_Contact as Contact".

In generated models, aliases should become model's names and original table names should go to TableName property of model.

P.S. Auto generating models for Sequelize mean that you dealing with some legacy database (or 3d party database), so you have no control about table names. But working with nice model names in code will make whole work nicer.

**Comment by deksden** [comment]
Here is pull request for this feature: https://github.com/sequelize/sequelize-auto/pull/83

Also - notice some fixes for prev code (some typos & additional checks). Sorry for bugs

**Comment by durango** [comment]
Closing issue and left a comment on the PR
