### ISSUE TITLE
CLI option: optionally generate foreign key references for models (default - true)

### ISSUE THREAD

**Issue by deksden** [sequelize/sequelize-auto#81]
IMHO, it can be optionally to generate FK references for models. 

Maybe after importing models, you will want to define relations/associations, and FK references will became obsolete.

**Comment by deksden** [comment]
PR for this feature: https://github.com/sequelize/sequelize-auto/pull/85

**Comment by durango** [comment]
You can programmatically remove these keys now by invoking `run`
