### ISSUE TITLE
Can I change fields name from snake case into lower camel case?

### ISSUE THREAD

**Issue by sjfkai** [sequelize/sequelize-auto#86]
I use snake case(like `hello_world`) in my db tables, but I want  the field in the model was like 

```
helloWorld: {
  type: DataTypes.STRING,
  field: 'hello_world',
  allowNull: true
}
```

Can I do this with sequelize-auto ?

**Comment by deksden** [comment]
AFAIK, it is not currently possible. 

But, this is useful feature, and it will be relatively easy to implement. If i will have time in this week, i ll try to implement it.

**Comment by sjfkai** [comment]
@deksden 👍   Thanks!

**Comment by philarmour** [comment]
👍

**Comment by durango** [comment]
You technically can with using the programmatic API https://github.com/sequelize/sequelize-auto#programmatic-api but you would still need to dump that new output somewhere

**Comment by sjfkai** [comment]
@durango I create a PL #89 to make `sequelize-auto` could do this.

**Comment by durango** [comment]
Closing the issue due to #89 thanks @sjfkai

**Comment by rambabusaravanan** [comment]
@durango  Thanks that camelCase option is happily available in command line option.
Can you implement the same camelCase option in [Programmatic API](https://github.com/sequelize/sequelize-auto#programmatic-api) with an example.

**Comment by sjfkai** [comment]
@rambabusaravanan  Just:

```js
var SequelizeAuto = require('sequelize-auto')
var auto = new SequelizeAuto('database', 'user', 'pass');

auto.run(function (err) {
  if (err) throw err;

  console.log(auto.tables); // table list
  console.log(auto.foreignKeys); // foreign key list
});

With options:
var auto = new SequelizeAuto('database', 'user', 'pass', {
    host: 'localhost',
    dialect: 'mysql'|'mariadb'|'sqlite'|'postgres'|'mssql',
    directory: false, // prevents the program from writing to disk
    port: 'port',
    camelCase: true,
    additional: {
        timestamps: false
        //...
    },
    tables: ['table1', 'table2', 'table3']
    //...
})
```

**Comment by rambabusaravanan** [comment]
@sjfkai Perfect. This is working as expected ..
Team, please document the missing items like this ..
