### ISSUE TITLE
Why covert tinyint(1) into BOOLEAN?

### ISSUE THREAD

**Issue by sjfkai** [sequelize/sequelize-auto#91]
Why covert tinyint(1) into BOOLEAN?

Fileds with type tinyint(1) can save `0-9`. Isn't it?

**Comment by sushantdhiman** [comment]
Although we can use `BIT` type to store `boolean` its not possible to achieve cross dialect support. `SQLite` for example doesn't support `BIT` type.

**Comment by sjfkai** [comment]
@sushantdhiman Yes! But I think we couldn't covert `tinyint(1)` into `BOOLEAN ` directly. Maybe someone use `tinyint(1)` to store `0-9` rather than `BOOLEAN`.

**Comment by durango** [comment]
In order to support older versions of Sequelize

**Comment by awcchungster** [comment]
When I run sequelize auto (0.7.11) on a MySQL Database (5.7), my tinyint booleans are converting to tinyints/number in the models. Is that intentional? If so, should I convert all my booleans into 0/1 when creating a model?

**Comment by steveschmitt** [comment]
@awcchungster On MySQL, you should use the BIT datatype to represent booleans.

**Comment by awcchungster** [comment]
Hi @steveschmitt! Thanks for the follow up. Do you have a quick example I can reference?

**Comment by steveschmitt** [comment]
You can look at the **mysql-sample-model.sql** script in the [sample/dbscripts](https://github.com/sequelize/sequelize-auto/tree/master/sample/dbscripts) directory.
