### ISSUE TITLE
Generate models from SqlExpress

### ISSUE THREAD

**Issue by johnmurphy01** [sequelize/sequelize-auto#92]
I have a SQL Express instance running on a local machine that I can connect to remotely.

I have authenticated the connection between Sequelize and the sql server instance from within Node.js. Now I want to be able to generate my models based on the existing tables.

I've added a config.js file for the CLI. This is my command:

```
sequelize-auto -o "./db_models" -d MaintToolkit -h 192.168.200.38 -u sa -x password -e mssql -c "config.js"
```

Here is my config.js file contents:

```
module.exports = {
    dialectOptions:{instanceName:'sqlexpress'},
     pool: {
                max: 5,
                min: 0,
                idle: 10000
            }
}
```

when I run this, I get "Login failed for user \'sa\'.'

I am able to connect to the instance using Sql Server management studio. I am supposedly able to connect to the instance running the authenticate method from Sequelize(as in, the authenticate method does not throw any errors). I am able to ping the IP address successfully.

Is there something wrong with the config file? I suspect this has something to do with running sqlexpress. Any help would be appreciated.

**Comment by johnmurphy01** [comment]
I figured out my issue. The password value has to have ' (single quotes) around it. Double quotes does not work and no quotes does not work. That should probably be included in the docs, but maybe I just didn't know what I was doing. :) Thanks and I hope this helps someone else!

**Comment by durango** [comment]
Closing this issue since you've resolved it yourself. Thanks :+1:
