### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by TitaneBoy** [sequelize/sequelize-auto#94]
Hello everyone. First of all, thank you again for this great tool you have done here. However, my question is:  Is it possible to have a changelog file just to be aware of what changed between each versions of sequelize-auto ?. You can see an exemple of changelog in the sequelize package:  [Sequelize Changelog](https://github.com/sequelize/sequelize/blob/master/changelog.md)

Thank you in advance for your answer.

**Comment by durango** [comment]
Changelog has been added

**Comment by TitaneBoy** [comment]
Thank you :-)
